### ISSUE TITLE
line 713 eve/methods/common.py  does not work returns none

### ISSUE THREAD

**Issue by ydaniels** [pyeve/eve#1000]
This code returns none instead of the embedded document 
```
embedded_doc = app.data.find_one(subresource, None,
                                         **{id_field: reference.id
                                            if isinstance(reference, DBRef)
                                            else ObjectId(reference)})
```

While this works properly 
`app.data.driver.db[subresource].find_one({id_field: reference})`

**Comment by Amedeo91** [comment]
Hi, find_one merge the query you provided with the filter you defined in the resource set-up (field filter in the data_source)

![image](https://user-images.githubusercontent.com/8645312/27392328-b359a814-56a6-11e7-8223-98cdcc576076.png)

You should check if this is what it generates your issue.

Regards,
Amedeo
