### ISSUE TITLE
How to set User Define endpoints

### ISSUE THREAD

**Issue by Sanat017** [pyeve/eve#1005]
I want to restrict every  http request method except post and set user_id as an endpoint , i have tried for additional lookup field but it wont help me out .
So can you please suggest me what i should do ?
Thanks

**Comment by luiscoms** [comment]
I guess that what are you looking is the configuration:

    ITEM_METHODS = ['GET', 'PATCH', 'PUT']
    PUBLIC_ITEM_METHODS = ['POST']

**Comment by nicolaiarocci** [comment]
If you only want clients to be able to POST, then @luiscoms suggestion goes in the right direction. Maybe even set `ITEM_METHODS = []`, or maybe `['GET']`.
