### ISSUE TITLE
Pagination as a resource setting

### ISSUE THREAD

**Issue by gwainer** [pyeve/eve#1008]
I know pagination is a global setting, but it would be good to be able to disable/enable pagination in specific resources, overriding the global setting. 

For now, as a workaround you can set the global `PAGINATION_LIMIT` to a large value affecting all the resources, and then pass the request parameter `max_results` with that large value to have one large page, which is not ideal.

**Comment by nicolaiarocci** [comment]
Looks like a good idea. We could have `pagination` at endpoint level.

**Comment by nicolaiarocci** [comment]
Actually, 'pagination' is there (and has been for a good while).
