### ISSUE TITLE
Leaking default object modifications

### ISSUE THREAD

**Issue by bustawin** [pyeve/eve#1016]
Objects set as default are not `copy.copy` to new documents, so modifying those objects in the document modifies them in the default clause, and then the modification is applied by default to newer documents.

Something similar to this typical python behavior: `def func(a = []):` and then modifying `a`.

I am sorry that I cannot try now in the newest eve release (mine is 0.6.4) but I don't see it addressed in the changelog nor issues. I can check it in the following days if needed and comment again.

**Comment by nicolaiarocci** [comment]
Could you please let me know which version of Cerberus you are using? Thanks!

**Comment by bustawin** [comment]
Sure. It is the last possible with that version of eve; 0.9.2.
