### ISSUE TITLE
Does validation apply on items modified in a before insert hook?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [pyeve/eve#1020]
I'm experiencing an odd behavior. I post some data in the format {"content": "xml_string"} then I use a before insert hook to transform this xml string into json and the document is correctly inserted in the database but the schema validation is not applied to the "transformed" item. The format that the xml document is modified to, matches the schema defined in my settings.py.

I made some tests and if I stop using the before hook and apply the transformation to the xml before I request.post to the API, the validation occurs normally. I'm gessing that the validation happens before any hooks are called... Am I correct to assume this? If so, is there a way to programatically "recall" the validation from inside the hook?

Thanks

**Comment by Amedeo91** [comment]
The validation occurs between the on_PRE_<HTTP_METHOD> callback and the database callback.

I did not really understand your use case and why you need to manually convert the string to XML, but you can call in a custom way the validator as follow. By the way, given you usecase, ài will not suggest to do it so, but I would sugget to do the convertion in the on_PRE_<HTTP_METHOD> callbacks.

You need to get the validator setting the schema and the resource as follow:
schema = resource_def['schema']
validator = app.validator(schema, resource=resource) #where app is the current_app in Flask

validation = validator.validate(document) 
#For PATCH uses validate_update(updates, object_id, original)
#For PUT uses validate_replace(updates, object_id, original)

validation is true if the validation was successful
