### ISSUE TITLE
Application does not tun after flask-pymongo update to 0.5.1

### ISSUE THREAD

**Issue by luiscoms** [pyeve/eve#1022]
When application starts this error occurs:

/python3.4/site-packages/flask_pymongo/__init__.py", line 278, in init_app
    auth_mechanism = app.config[key('AUTH_MECHANISM')]
KeyError: 'MONGO_AUTH_MECHANISM'

My alternative solution is to fix flask-pymongo to 0.4.1

**Comment by nicolaiarocci** [comment]
Ah great, thanks for the heads up. We're moving away from Flask-PyMongo, see #1014.
