### ISSUE TITLE
document_etag not matching

### ISSUE THREAD

**Issue by lomby92** [pyeve/eve#1039]
I'm writing a custom endpoint and i want to evaluate current ETag of the document (using MongoDB).
If i do `GET /myEndpoint/:id` EVE framework attach **_etag** field and i can use it in `PUT /myEndpoint/:id` on If-Match header.
On server side i want to check If-Match header using Eve native function **eve.utils.document_etag()** on document from database.
Why Eve-calculated etag is different to etag calculated on my PUT handler?

**Comment by Amedeo91** [comment]
It is not clear what it is not working for you: could you please share your code or something like that?
