### ISSUE TITLE
Add UUID support

### ISSUE THREAD

**Issue by lomby92** [pyeve/eve#1041]
MongoDB can use UUID instead of ObjectId, why Eve doesn't support it?
Python have [uuid module](https://docs.python.org/3.6/library/uuid.html#module-uuid), can be used to edit **eve.io.mongo.validation.Validator.**?
For example:
```python
from uuid import UUID

def _validate_type_uuid(self, value):
        if isinstance(value, UUID):
            return True

```

**Comment by nicolaiarocci** [comment]
There is actually a tutorial on how to add support for UUID fields, see: http://python-eve.org/tutorials/custom_idfields.html#handling-uuid-fields

**Comment by lomby92** [comment]
I have tried but using this line (in UUIDEncoder class):
```python
return super(UUIDEncoder, self).default(obj)
```
doesn't work.

Maybe is due i want to use ObjectId as `_id` and UUID for external fields in schemas?

**Comment by lomby92** [comment]
**Solved**
In my project i want to use ObjectId and UUID, `BaseJSONEncoder` doesn't have support for ObjectId so i have tryied with `MongoJSONEncoder` from `eve.io.mongo` and it works.

Solution:
```python
from eve.io.mongo import MongoJSONEncoder
from uuid import UUID


class UUIDEncoder(MongoJSONEncoder):
    """ JSONEconder subclass used by the json render function.
    This is different from MongoJSONEoncoder since it also addresses
    encoding of UUID
    """

    def default(self, obj):
        if isinstance(obj, UUID):
            return str(obj)
        # use EVE encoder to all remaining data
        return super(UUIDEncoder, self).default(obj)
```

@nicolaiarocci if you want, add this to tutorial.
