### ISSUE TITLE
Wrong ordering due to not enough time granularity

### ISSUE THREAD

**Issue by bustawin** [pyeve/eve#1043]
Sometimes I get wrong order retrieving documents from MongoDB using `_created` because the documents were inserted in the same second and the granularity of `_created` is not enough.

As I understand from looking at the code in `post_internal`, `_created` and `_updated` values are saved with a max of granularity of seconds, without any possibility of changing it. Am I correct?

Note that a workaround (not elegant solution) is to replace those values in a hook.

**Comment by petrjasek** [comment]
you can use order by `_id` that will be consistent and will use an index as well

**Comment by petrjasek** [comment]
but that doesn't work for `_updated` obviously :wink:

**Comment by bustawin** [comment]
In case you use the _id with the objectId of MongoDB, otherwise... :-)

Maybe the granularity could follow the format of the date_format setting (or a specific similar setting)?

**Comment by Amedeo91** [comment]
I think this is a specific need for your application: can't you add a hook event that generates a sorting index for your purpose? Otherwise, I guess that the _id is the best option as it contains the time of creation of the record: https://docs.mongodb.com/manual/reference/method/ObjectId/
