### ISSUE TITLE
Support for MongoDB Decimal type

### ISSUE THREAD

**Issue by theothermatt** [pyeve/eve#1045]
This is a feature request for support for the newly added MongoDB Decimal type:

https://docs.mongodb.com/master/release-notes/3.4/#decimal-type

I'm sure you've got plenty of things to do, I just wanted to make sure it was on the radar!

Thanks,

Matt

**Comment by Amedeo91** [comment]
Hi,

how do you need this feature to be supported? By default or with some schema set-up?

Regards,
Amedeo

**Comment by Amedeo91** [comment]
@nicolaiarocci should it be a default behavior or should it be a set-up in same places of the schema?

This is how to support it: https://api.mongodb.com/python/3.4.0/api/bson/decimal128.html

**Comment by theothermatt** [comment]
@Amedeo91 not quite sure what you mean by 'default or with some schema set-up', but I guess I had pictured it as being done by a `'type': 'decimal'` line in the schema.

A nice extra would be the ability to validate based on the number of decimal places.  For example, reject a value with more than 2 decimal places.  Of course, this could be done with custom validation rules.

**Comment by Amedeo91** [comment]
For the second point, I think it is more a specific need, hence it might be customized by the framework user.

For the first point, I was referring that Eve might store every number as decimal type in Mongo or either to specify a new type in the schema. @nicolaiarocci what would you suggest?

**Comment by Amedeo91** [comment]
Ok, I just did a small analysis: it would be enough to add the lamda function in the serializers dictionary inside the Mongo class in the file eve\io\mongo\mongo.py
However, then we have to update Cerberus aswell to validate the data type. For it, I think it should be enough to update the file validator.py adding the method def _validate_type_decimal(self, value). @nicolaiarocci : do you think there should be anything else to do? Maybe we should start to add this feature in Cerberus and after in Eve?

**Comment by nicolaiarocci** [comment]
@Amedeo91 On second thought (see you PR on Cerberus), couldn't you simply update [Eve's custom validator+(https://github.com/pyeve/eve/blob/master/eve/io/mongo/validation.py) instead of updating Cerberus core? It is true that Decimal makes support our of Eve's scope but, in fact, there have been no requests for that in Cerberus yet (except, of course, for Eve). 

WIth a single Eve PR we could add validation and serialization for Decimals. Thoughts?

**Comment by Amedeo91** [comment]
@nicolaiarocci, I was thinking the same thing this morning! :)

**Comment by Amedeo91** [comment]
I will try to do the PR this days! :)

**Comment by funkyfuture** [comment]
and i didn't dare to propose. :-)

**Comment by nicolaiarocci** [comment]
It's merged to master.
