### ISSUE TITLE
Simple endpoint-level authentication don´t work

### ISSUE THREAD

**Issue by Paindragon** [pyeve/eve#1046]
hi all,
i´m new at python and have a little problem.
i´m using 

- Ubuntu 64bit       16.04
- Eve                       0.7.4
- python                    3.6.1

now i use the same code as on the homepage (http://python-eve.org/authentication.html)

my "Server"-Script my_run.py looks like 

    from eve import Eve
    from eve.auth import BasicAuth

    class MyBasicAuth(BasicAuth):
        def check_auth(self, username, password, allowed_roles, resource,
                       method):
            return username == 'admin' and password == 'secret'

    app = Eve(auth=MyBasicAuth)

    @app.route('/hello')
    def hello_world():
        return 'hello world!'

    app.run()

and the standart settings file.

the Homepage says
> All your API endpoints are now secured, which means that a client will need to provide the correct credentials in order to consume the API

When i connect to the URL 127.0.0.1:5000 the messagebox with username and passwort works fine, but when i go to 127.0.0.1:5000/hello i get the informations without any authentication.

The terminal has following output

    python my_run.py

     * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

    127.0.0.1 - - [16/Aug/2017 15:18:14] "GET / HTTP/1.1" 401 -

    127.0.0.1 - - [16/Aug/2017 15:18:19] "GET / HTTP/1.1" 200 -

    127.0.0.1 - - [16/Aug/2017 15:18:19] "GET /favicon.ico HTTP/1.1" 404 -

    127.0.0.1 - - [16/Aug/2017 15:18:19] "GET /favicon.ico HTTP/1.1" 404 -

    127.0.0.1 - - [16/Aug/2017 15:18:23] "GET /hello HTTP/1.1" 200 -

What did i wrong?

**Comment by Amedeo91** [comment]
Can you provide some extra info? Like why you received 404 after the 200? 
However, my guess is that it is not working as you are registering the endpoint directly in Flask bypassing all the Eve logic. 

If you really need to use Flask based end-point and keep the Eve logic, you should have a look at the implementation of Eve and try to do the same call in order to perform the authentication!

Regards,
Amedeo

**Comment by Amedeo91** [comment]
Ok, my supposition was right. All the end point registered in Eve has the following decorator: @requires_auth('item') or @requires_auth('resource'). In you case, as you do not want to register in Eve, it will not work. But you can try to mimic the same behaviour with the following code:

def custom_authentication(endpoint_class, public_methods, allowed_roles, allowed_read_roles, allowed_write_roles):
	public = public_methods
	roles = allowed_roles
	if request.method in ['GET', 'HEAD', 'OPTIONS']:
		roles += allowed_read_roles
	else:
		roles += allowed_write_roles
	auth = app.auth
	if auth and request.method not in public:
		if not auth.authorized(roles, resource_name, request.method):
			return auth.authenticate()

I did not test it, therefore it might require some fixes.

Regards,
Amedeo

**Comment by Paindragon** [comment]
Thank you I think i found and understand the problem.

**Comment by nicolaiarocci** [comment]
You can actually leverage Eve's own auth logic for flask endpoint, see https://stackoverflow.com/questions/38160290/how-to-protect-custom-endpoints-using-basicauth/44148483#44148483 (and please vote up if it helps, so other readers know it's helpful too)

**Comment by nicolaiarocci** [comment]
Sorry, wrong link. I updated the answer above.
