### ISSUE TITLE
Embedded Resource Serialization

### ISSUE THREAD

**Issue by tzblic** [pyeve/eve#1054]
I have a document like this:
demo={

    'item_title': 'blog',

   
    'additional_lookup': {
        'url': 'regex("[\w]+")',
        'field': 'author'
        },

    'schema':{
       
        'author':{
            'type':'objectid',
            'data_relation':{
                'resource':'user',
                'field':'_id',
                'embeddable':True,
                },
            },

user={
    'item_title': 'user',

    'additional_lookup': {
        'url': 'regex("[\w]+")',
        'field': 'username'
    },

    'schema':{
        'username':{
            'type':'string',
            },

        'like':{
            'type':'list',
            'schema':{
                'type':'string',
                }

           },
       'friends':{
            'type':'dict',
            'schema':{
                'name':{'type':'string'},
                },

            },

When i visit a url like this   /demo/<_id>/?embedded={"demo":1}, How can I choose to display the specified fields of the user document？thanks very much.

**Comment by Amedeo91** [comment]
You should be able to use the projection parameter.

**Comment by tzblic** [comment]
I should be how to do specific, can give an example？thinks
