### ISSUE TITLE
Dockerfile or Docker Compose example

### ISSUE THREAD

**Issue by theodesp** [pyeve/eve#1059]
It would be nice if the project had an official Dockerfiler or a Docker Compose YAML specification for setting up a cluster, for example, MongoDB + Nginx + pyeve + uWSGI + supervisor

I could work on this week. What do you think?

**Comment by Amedeo91** [comment]
Go head!

**Comment by tgmendes** [comment]
I actually implemented Eve using all the resources you mentioned. I would be glad to make this code available in the repository!

**Comment by nicolaiarocci** [comment]
Sure, go ahead, maybe submit it to the scripts section of the documentation, or if you feel like doing it, write a tutorial for the tutorials section.

**Comment by nicolaiarocci** [comment]
Closing this for the time being. Open to review a PR, should anyone want to take a stab at it
