### ISSUE TITLE
$regex doesn't work

### ISSUE THREAD

**Issue by athlonUA** [pyeve/eve#1060]
I found the solution of case insensetive search on https://stackoverflow.com/a/31027960 But it doesn't work for me. I receive an error something like this 
```
<resource>
  <_error>
    <code>400</code>
      <message>
        The browser (or proxy) sent a request that this server could not understand.
      </message>
    </_error>
  <_status>ERR</_status>
</resource>

**Comment by Amedeo91** [comment]
Check that you request is correctly formed!

**Comment by domeniconappo** [comment]
@athlonUA can you show how you make the request? e.g. pasting here your curl command?

**Comment by athlonUA** [comment]
@domeniconappo Sorry, i cann't give you an access to my API. But I try to explain my problem below

On my site I need to find all the clients with name `Tomas`
My request url: `/api/users/?where={"name":{"$regex":"^(?i)tom.*"} }`

In the `settings.py` file i added 
```
MONGO_QUERY_BLACKLIST = ['$where']
```
to enable `$regex`

Users schema
```
users = {
    'schema': {
        'name': {
            'type': 'string',
            'required': True,
        },
        'surname': {
            'type': 'string',
        },
        ...
    }
}
```

But in response I received the error like this

```
<resource>
  <_error>
    <code>400</code>
      <message>
        The browser (or proxy) sent a request that this server could not understand.
      </message>
    </_error>
  <_status>ERR</_status>
</resource>
```

**Comment by domeniconappo** [comment]
@athlonUA 
Hi,
It can be an char escaping problem on client side...Which client you use to test the REST API?

I've made some tests vs my API using curl and had same errors. 

Finally, I managed to make it working: if you try in Linux the curl command from command line in this way (please note  "\" chars to escape "{" and "}". Also, wrap the address in single quotes chars so you can avoid to escape internal double-quotes chars (like this \") :

`curl -X GET 'http://localhost:8080/pullrequests?pretty&where=\{"JIRA":\{"$regex":"^(?i)jir.*"\}\}' -H  "accept: application/json"`

The call above works fine while the call below fails with the same error you reported:

`curl -X GET "http://localhost:8080/pullrequests?pretty&where=\{\"JIRA\":\{\"$regex\":\"^(?i)jir.*\"\}\}" -H  "accept: application/json"`
Just check into your webserver logs which is the actual request your server receives so you can find which characters are badly passed (probably the "$" character which is a reserved character as specified in RFC 2396 :) ).

For the last call (the bad one), in logs I see 
`GET /pullrequests?pretty&where={"JIRA":{"":"^(?i)jir.*"}} HTTP/1.1" 400`
As you see, the $regex keyword is not passing at all at the server, as it was purged. This leads exactly to that error.
