### ISSUE TITLE
Projection Not Working On Embedded Field

### ISSUE THREAD

**Issue by ydaniels** [pyeve/eve#1061]
e.G
```
accounts = {

'embedding':True,
'datasource': {
        'projection': {'password': 0}
        },
    'schema': {

'username': {
        'type': 'string',
        'min' : 2,
        'max' :20,
        'default' :'',
        },

'password': {
        'type': 'string',
        'min' : 2,
        'max' :20,
'default' :'',
        },
}, }

logs = {
schema : {
'account': {
        'type': 'objectid',
        'data_relation': {
            'resource': 'accounts',
            'field': '_id',
            'embeddable': True,
        },
    },
}
```
 a get requests on accounts resource works very well i.e password not returned
`{'username':'value'}`

but a get request on` /logs?embedded={account:1} `returns 
`{'account':{'username':'value','password':'value'}}`

password is suppose to be hidden

**Comment by Amedeo91** [comment]
Projection declare on "father doc" are not applied in the embedded doc. To make it work, a PR is required

**Comment by ydaniels** [comment]
okay understood i'll create a pull request  .

**Comment by Amedeo91** [comment]
Try not to go in conflict with this #1033
