### ISSUE TITLE
mongo_indexes

### ISSUE THREAD

**Issue by tzblic** [pyeve/eve#1063]
I want to achieve this function  like  db.collection.createIndex({'fristname':1,'lastname':1,unique:1})
How should i do it in eve，
'mongo_indexes':{
      'index_name':[('firstname',1),('lastname',1)],
        }
Thinks

**Comment by Amedeo91** [comment]
You need to use the same syntax you have for pymongo when you call createIndex. 

Let me know if you need a specific example or you are able by yourself reading pymongo documentation

Regards

**Comment by tzblic** [comment]
@Amedeo91 Your means that i  do not have to set mongo_indexes in eve schema, but use pymongo?

**Comment by Amedeo91** [comment]
No, I meant that mongo_index require the indexes you want to create defined as per pymongo:

Indexes are expressed as a dict where keys are index names and values are either a list of tuples of (field, direction) pairs, or a tuple with a list of field/direction pairs and index options expressed as a dict, such as {'index name':[('field', 1)], 'index withargs': ([('field', 1)],{"sparse": True})}.

You definition is wrong. I found the above in the eve documentation

**Comment by tzblic** [comment]
@Amedeo91 In fact, I want two fields to implement unique, but not every one is unique, just like sql's unique (field1, field2) 
Thanks for your reply。

**Comment by Amedeo91** [comment]
This work fine for me:

'mongo_indexes': {
        'unique_id': ([('field' 1),
                       'field2', 1)], {'unique': True})
}

Just check that you put this set-up in the DOMAIN --> <resource_name> of you eve setting

Regards,
Amedeo
