### ISSUE TITLE
Confusing terms in documentation and configuration for resource/collection/item

### ISSUE THREAD

**Issue by domeniconappo** [pyeve/eve#1065]
Maybe a minor issue or not an issue at all.

In REST API design domain, a singleton resource (or simply a __resource__) is a single object while a collection resource (or simply a __collection__) is a collection of singleton resources.
I've noticed that in Eve, both in documentation and in configuration:

- the term _resource_ is used instead of _collection_ 
- the term _item_ is used instead of _resource_

Can't this lead to sort of confusion?

References:
http://restful-api-design.readthedocs.io/en/latest/methods.html
https://www.thoughtworks.com/insights/blog/rest-api-design-resource-modeling
http://restful-api-design.readthedocs.io/en/latest/resources.html

**Comment by nicolaiarocci** [comment]
Yes, I agree that it can lead to confusion. Feel free to submit a PR for this.

**Comment by domeniconappo** [comment]
@nicolaiarocci 
Thanks. I will be happy to contribute. 

Do you think it's better to address this only in documentation (just by adding a few warning notes on terminology used in Eve) or also by changing related config variables names (need deprecation)?

In the latter case we need to deprecate current variables, adding new ones whose names better reflect the REST API terms, and managing both. This also means raising a deprecation warning in case the user is configuring the deprecated one (because he updated Eve while uses the existing settings).

I can't replace ITEM_METHODS with RESOURCE_METHODS because this variables is already used for collection resource (in case we want to deprecate) so I would suggest following names:

- ITEM_RESOURCE_METHODS and deprecate ITEM_METHODS
- COLLECTION_RESOURCE_METHODS and deprecate RESOURCE_METHODS

Please, provide feedback on this. Thanks!
