### ISSUE TITLE
If I send `DELETE` request to any of my endpoint list all my data will be lost

### ISSUE THREAD

**Issue by athlonUA** [pyeve/eve#1066]
If I send `DELETE`request to any of my endpoint list, e.g.`/talks`, all the objects from my collection will be removed
![image](https://user-images.githubusercontent.com/9050727/30657145-36760b54-9e3f-11e7-88ab-cad4a98aa85d.png)

**Comment by Amedeo91** [comment]
This is the wanted behaviour. Check the documentation!!
