### ISSUE TITLE
Problem implementing get for S3 custom MediaStorage class

### ISSUE THREAD

**Issue by gwainer** [pyeve/eve#1067]
Using eve 0.7.4, I'm trying to implement a `MediaStorage` class to store and retrieve data from AWS S3.  I am following documentation information and checked a similar question on [SO](https://stackoverflow.com/questions/21823649/how-to-upload-image-through-python-eve-to-some-external-storage-server-e-g-s3/21824645#21824645).

I've found an issue with `get` implementation and need help to check if there's any workaround to make it work.

First, the code for the custom `MediaStorage` is the following:

```
from eve.io.media import MediaStorage
from flask.app import Flask
import boto3
from tiquetaque_api.config.config_parser import config
from bson.objectid import ObjectId

BUCKET = config.get('s3', 'bucket')

class S3MediaStorage(MediaStorage):
    def __init__(self, app=None):
        super(S3MediaStorage, self).__init__(app)
        self.validate()
        self.s3 = boto3.client('s3', aws_access_key_id=config.get('s3', 'key'),
                               aws_secret_access_key=config.get('s3', 'secret'),
                               region_name=config.get('s3', 'region'))

    def validate(self):
        if self.app is None:
            raise TypeError('Application object cannot be None')

        if not isinstance(self.app, Flask):
            raise TypeError('Application object must be a Eve application')

    def exists(self, id_or_filename, resource=None):
        # TODO
        return True

    def get(self, id_or_filename, resource=None):
        self.s3.download_file(BUCKET, id_or_filename, id_or_filename)
        file = open(id_or_filename, mode='rb')
        return file

    def delete(self, id_or_filename, resource=None):
        # TODO
        pass

    def put(self, content, filename=None, content_type=None, resource=None):
        _id = str(ObjectId())
        self.s3.upload_fileobj(content, BUCKET, _id)
        return _id
```
Nevermind `exists` and `delete`, still work to do.

 ### Problems encountered when doing HTTP GET to /media item endpoint (and workarounds found):
- Issue using UUIDv4 as item ID. Route leads to HTTP `404` on `/media GET` even if the `POST` went OK.
    Since I've tried to use UUIDv4 as ID for the media files, the `put` method from `S3MediaStorage` was returning an UUIDv4 format. This return value is used to build the /media item URL. Using this format mentioned, a routing exception was raised by flask ([permalink](https://github.com/pallets/flask/blob/c72e7c7c70f1553295022c70d5058ed11932c16a/flask/app.py#L1453)), leading to a `404` response.
**Workaround:** Use `oid` format as ID for the media files (`S3MediaStorage.put` return value). This solved the problem and I could go further. I suspect that eve's the registered route for media endpoint expects an ObjectID format, and does not match any other format. Can this be changed?

- Function `media_endpoint` expects some properties not found inside the return from `S3MediaStorage.get`:
In endpoints.py, around line 191 inside `media_endpoint` function ([permalink](https://github.com/pyeve/eve/blob/cee2f7ec13976f5bc3910f7058648a8b33ec882c/eve/endpoints.py#L191)), after retrieving the file using my MediaStorage implementation, the code below:

```
    if_modified_since = weak_date(request.headers.get('If-Modified-Since'))
    if if_modified_since is not None:
        if if_modified_since.tzinfo is None:
            if_modified_since = if_modified_since.replace(
                tzinfo=tz_util.utc)

        if if_modified_since > file_.upload_date:
            return Response(status=304)

    headers = {
        'Last-Modified': date_to_rfc1123(file_.upload_date),
        'Content-Length': file_.length,
    }

```
 Expects properties in the file that are not present. Values such as `length, content_type, upload_date` exists when using GridFS (in the `GridOut` returned instance), but in my case I don't have the fields. The returned type is an open file (`BufferedReader` class). 
So I ask, what other kind of buffer or stream can I use in the response to inject the needed fields in the return value for `get` to make it work? 

Thanks.

**Comment by gwainer** [comment]
Well. I've found a way to work around this by creating an iterable class, similar to GridOut, and using an instance as return value for the `get` method from the custom `MediaStorage` class. Code is below:

```
from datetime import datetime

class S3Out(object):
    def __init__(self, file: str, content_type: str, upload_date: datetime, length: int):
        self.file = file
        self.content_type = content_type
        self.upload_date = upload_date
        self.length = length

    def __iter__(self):
        return open(self.file, mode='rb')
```

**Comment by Guibod** [comment]
@gwainer please let me know if you are willing to share this piece of code with the outer world, I'm in a need of such of an implementation right now.

**Comment by gwainer** [comment]
Sure, I can do this. But now I’m off for two weeks. When returning, I can make a fork for you to check.

Regards,

Gabriel Wainer

**Comment by gwainer** [comment]
Hi @Guibod, please check this commit here, it contais the S3 storage media implementation. 

Made some raw adjustments from my code. You need to retrieve from configuration or set your own AWS credentials at the start of s3_storage.py to make it work.

https://github.com/gwainer/eve/commit/eaf1c0adc2ef6c7d66e429bc70104f5808b841d8

**Comment by gwainer** [comment]
I believe this issue can be closed, since I've managed to solve the issues with S3 media storage implementation.
