### ISSUE TITLE
Embedding only follows _id 

### ISSUE THREAD

**Issue by scholzd** [pyeve/eve#1069]
I have the following schemes:

    nodes = {
        'type': 'dict',
        'schema': {
            'hardware': {
                'type': 'string',
                'data_relation': {
                    'resource': 'nodes_hw',
                    'field': 'name',
                    'embeddable': True
                }
            }
        }
    }

    nodes_hw = {
        'type': 'dict',
        'schema': {
            'name': {
                'type': 'string',
                'required': True,
                'unique': True
            }
        }
    }

When now querying 

    /nodes?embedded={"hardware":1}

the resulting value for hardware is null.

The following lines seem to be the problem
https://github.com/pyeve/eve/blob/cee2f7ec13976f5bc3910f7058648a8b33ec882c/eve/methods/common.py#L826-L829

Internally, in nodes_hw a lookup is performed with _id = VALUE_OF_HARDWARE.

Changing this line to use data_relation['field'] yields the expected result.
Then the internal lookup is correctly performed with name = VALUE_OF_HARDWARE
As result, hardware contains a dictionary with the embedded nodes_hw object.

Am I doing something wrong, is this not wanted or is this a bug?

**Comment by Amedeo91** [comment]
For the timw being, embedded document can be references using the id_field in the resource configuration. 

You can use the code in the PR #1033 in order to costonize the research in the "child" document using the hook event.

**Comment by scholzd** [comment]
Thanks for the info!

**Comment by einarhuseby** [comment]
@nicolaiarocci and @Amedeo91, have been running into a similar case as @scholzd ,and it looks like `data_relation["field"]` is not honored or am I missing something?

https://github.com/pyeve/eve/blob/e3838be901833b2de0eb298d37f784f743f23141/eve/methods/common.py#L905-L911

For now I'm using the following, honoring `DBRef` and fallback to `id_field`:
```
id_field_name = (
    "_id"
    if isinstance(reference, DBRef)
    else data_relation.get("field", False) or config.DOMAIN[subresource]["id_field"]
 )
```
Or is this unintentionally opening a can of worms?
