### ISSUE TITLE
OPLOG =True is not working currently,

### ISSUE THREAD

**Issue by cst4049** [pyeve/eve#1074]
eve/methods/common.py
in v0.8
    if not config.OPLOG \
            or op not in config.OPLOG_METHODS\
            or resource in config.URLS[resource]: 
        return
in v0.7 and preview
    if not config.OPLOG or op not in config.OPLOG_METHODS: 
        return
it works in v0.7,and not work in v0.8

**Comment by Amedeo91** [comment]
Share your configuration please

**Comment by cst4049** [comment]
# oplog 
OPLOG = True
OPLOG_ENDPOINT = 'oplog'
I found common.py is different between  branch v0.6 to branch v0.8

**Comment by zhangtemplar** [comment]
I have the same problem. 

```
OPLOG = True
OPLOG_METHODS = ['GET', 'DELETE', 'POST', 'PATCH', 'PUT']
```
this configuration doesn't work either.

What is `resource in config.URLS[resource]` targeted for?

**Comment by cst4049** [comment]
oplog might be not record the GET method,
and your can try config.URLS[resource] not contain the resouce,
 like this: 
resource = "people" and the url must be not contain people 
you can use url like "human" and "aaa" something others just avoid "people"
the point is the url can't contain the resource name

**Comment by zhangtemplar** [comment]
@cst4049 I have commented out `resource in config.URLS[resource]` but still doesn't work.

**Comment by josemifv** [comment]
Hi all, 

I am currently working with Eve 0.7.4 and I have the same issue. After setting OPLOG=TRUE and OPLOG_ENDPOINT='oplog', the endpoint is created, but it is not populated.

After checking the source code, I noticed that the commit [a7350d](https://github.com/pyeve/eve/commit/a7350d08f4fc2e5155cf62e8f618401df14cb482#diff-825050a972dfddbdacccc7c0a830719b) fixed the issue, but the commit [662924](https://github.com/pyeve/eve/commit/6629241adb3c3615a0214fb2aa3f6da3929feb44#diff-825050a972dfddbdacccc7c0a830719b) changed the condition to the above-mentioned `resource in config.URLs[resource]` and the oplog_push does nothing as the initial condition always is True.

I changed the condition as coded in [a7350d](https://github.com/pyeve/eve/commit/a7350d08f4fc2e5155cf62e8f618401df14cb482#diff-825050a972dfddbdacccc7c0a830719b) and the OPLOG is working again in 0.7.4.

I hope it helps you :)

@zhangtemplar I have checked [eve/methods/get.py](https://github.com/pyeve/eve/blob/master/eve/methods/get.py) and oplog for GET method is not supported.

**Comment by zhangtemplar** [comment]
@josemifv Yes, I whitelist the get methods for oplog. But I find none of the methods, e.g., post, get, is ever logged.
