### ISSUE TITLE
There's no way to easily specify the latest version of a related resource

### ISSUE THREAD

**Issue by fernandocamargoti** [pyeve/eve#1080]
I have a versioned resource called **task** and another resource called **experiment** with a "data_relation" to **task** and version=True.

Everything works fine, but everytime I need to POST a new **experiment**, I need to set both _id and _version of the **task**. Shouldn't be a way to specify "latest"? Or maybe just specify the _id and the eve automatically understand it as the latest version.

**Comment by Amedeo91** [comment]
I do not think your usage of the version feature was what the developer had in his mind. I am not an expert of it, but I would suggesta to have a look at the code and then provide a PR is necessary
