### ISSUE TITLE
Do not accept POST request from Axios

### ISSUE THREAD

**Issue by narnikgamarnikus** [pyeve/eve#1082]
Hello!

If I send post request from `httipe` like this `http http://127.0.0.1:5000/messages text=HelloWorld`, all is well, and i get this server answers:

```
127.0.0.1 - - [03/Nov/2017 22:41:13] "OPTIONS /messages HTTP/1.1" 200 -
127.0.0.1 - - [03/Nov/2017 22:52:45] "POST /messages HTTP/1.1" 201 -
```

But, if I try send POST from axios, like this:

```
      axios.post(`http://127.0.0.1:5000/messages`, {
        text: JSON.stringify(data)
      })
        .then(response => {
          console.log(response)
        })
        .catch(e => {
          console.log(e)
        })
```

server return just OPTIONS:

`127.0.0.1 - - [03/Nov/2017 22:41:13] "OPTIONS /messages HTTP/1.1" 200 -`

POST does not reach the request. I do not understand what's the matter.

My settings:

```
RESOURCE_METHODS = ['GET', 'POST', 'DELETE']
PUBLIC_METHODS = ['GET', 'POST']
ITEM_METHODS = ['GET', 'PATCH', 'PUT', 'DELETE']
PUBLIC_ITEM_METHODS = ['GET', 'PATCH', 'PUT']

X_DOMAINS_RE = '*'

X_DOMAINS = '*'
```

**Comment by nicolaiarocci** [comment]
This looks like a client issue. Please use StackOverflow for this kind of inquiries.
