### ISSUE TITLE
No _meta on aggregate

### ISSUE THREAD

**Issue by dethstar** [pyeve/eve#1089]
Hello, I tried searching for this but found nothing. So, sorry if this is a dupe.
Basically, when I use an endpoint without aggregate I do get the _meta item. However, when I do something like this: 

'totalTypes' : {

        'datasource':{

            'source' : 'data',

            'aggregation' : {

                'pipeline': [

                    { "$match": "$match"
                    },

                    {"$group" : {

                        "_id": "$type",
                	 "amount": {"$sum": "$total"},
                        "type": {"$addToSet": "$type"}

                    }},
                    {"$sort" : {

                        "amount" :-1

                    }},
                    {"$project": {

                        "amount": '$amount',
                        "type": '$type',

                    }},
                ]
            }
        }

It does not work. I don't know if it is because I'm using aggregate? Couldn't find anything on the docs regarding that. Also, while I don't get a _meta, both max_results and page parameters still work.

**Comment by zhangtemplar** [comment]
It is intended behavior, according to [Limitations](http://python-eve.org/features.html#id8):
```
HATEOAS is not available at aggregation endpoints.
```
