### ISSUE TITLE
EVE don't work in docker

### ISSUE THREAD

**Issue by Rodrigocg** [pyeve/eve#1093]
Good Everning,

I've run eve in docker container, but eve return one error:
`
ssh://root@192.168.99.100:2201/envs/pycharm/bin/python -u /root/eveProject/app.py
Traceback (most recent call last):
  File "/root/eveProject/app.py", line 4, in <module>
    from eve_sqlalchemy.validation import ValidatorSQL
  File "/envs/pycharm/lib/python3.5/site-packages/eve_sqlalchemy/validation.py", line 18, in <module>
    from eve.utils import config, str_type
ImportError: cannot import name 'str_type'
`

All packages has installed. but I not find error. My python version is 3.5.

I don't understand the cause error of the import 'str_type', but eve work in my interpreter in local machine.

**Comment by nicolaiarocci** [comment]
This looks like an issue with eve-sqlalchemy, should be moved there: https://github.com/pyeve/eve-sqlalchemy

**Comment by Rodrigocg** [comment]
Ok! Sorry
