### ISSUE TITLE
How can I use custom oplog model with eve-sqlalchemy

### ISSUE THREAD

**Issue by amoyiki** [pyeve/eve#1094]
When i use eve-sqlalchemy created a oplog model and set `OPLOG=True` and `OPLOG_NAME='oplog'`.
but eve return one error:
```
Traceback (most recent call last): 
File "...\env\lib\site-packages\eve_sqlalchemy\__init__.py", line 196, in _get_model_attributes
  elif field in schema and schema[field]['type'] in ('list', 'set'):
KeyError: 'type'
```
because of in `eve.flaskapp`  is hardcode oplog schema
```python
...
def _init_oplog(self):
    settings['schema'] = {
            'r': {},
            'o': {},
            'i': {},
        }
...
```
so, please tell me how to do.

**Comment by nicolaiarocci** [comment]
This should be posted in the eve-sqlalchemy repository at https://github.com/pyeve/eve-sqlalchemy

**Comment by opensorceror** [comment]
Got this to work. Posting it here, in case it helps anyone. Had to do the following:
1. Had to fork Eve 0.7.10 (the latest version supported by eve-sqlalchemy) and and integrate [this fix](https://github.com/pyeve/eve/pull/1095) into my fork.
2. Unfortunately, [eve hardcodes the oplog schema](https://github.com/pyeve/eve/blob/v0.7.10/eve/flaskapp.py#L979), so even after defining the model using sqlalchemy, eve would simply overwrite the schema and consequently fail. I had to add a `on_oplog_push` hook to re-overwrite the schema.

My final configs look as follows:

**Sqlalchemy model**:
```python
class CommonColumns(Base):
    """Common columns"""

    __abstract__ = True
    _created = Column(TIMESTAMP, default=func.now())
    _updated = Column(TIMESTAMP, default=func.now(), onupdate=func.now())

class Oplog(CommonColumns):
    """Model that stores operational logs"""

    __tablename__ = "oplog"
    o = Column(String(10))
    r = Column(String(100))
    i = Column(String(100))
    c = Column(JSON(100))
    ip = Column(String(30))
    u = Column(String(50))
    _id = Column(Integer, primary_key=True, autoincrement=True)
```

**App settings**:
```python
DOMAIN = DomainConfig({"oplog": ResourceConfig(Oplog)}).render()
IF_MATCH = False
HATEOAS = False

# Oplog
OPLOG = True
OPLOG_CHANGE_METHODS = ['PATCH', 'PUT', 'DELETE', 'POST']
OPLOG_AUDIT = True
OPLOG_NAME = "oplog"
```

**Oplog push hook**:
```python
def oplog_extras(resource, entries):
    schema = DOMAIN['oplog']['schema']

    app.config["DOMAIN"]['oplog']["schema"] = schema

app.on_oplog_push += oplog_extras
```
