### ISSUE TITLE
Possible to use JSON Patch with Eve?

### ISSUE THREAD

**Issue by JamesRamm** [pyeve/eve#1099]
Is it possible to configure eve to use the JSON Patch standard for PATCH requests?

This makes it a lot easier to update a nested resource - E.g an array of objects where you want to change a single value in the 3rd object of the array for example. 

Any ideas on how to implement this using Eve?

https://tools.ietf.org/html/rfc6902
http://jsonpatch.com/

**Comment by nicolaiarocci** [comment]
Has this been solved with the introduction of `MERGE_NESTED_DOCUMENTS` in v0.8?
