### ISSUE TITLE
Where can I report security vulnerability?

### ISSUE THREAD

**Issue by orangetw** [pyeve/eve#1101]
Hi, I found a potential vulnerability in the latest version of Eve.
Is there any security related email I can send my report?

Thanks :)

**Comment by nicolaiarocci** [comment]
please send an email to eve@nicolaiarocci.com, thanks.

**Comment by orangetw** [comment]
I have sent, please check the inbox.

**Comment by orangetw** [comment]
`io/mongo/parser.py` in Eve (aka pyeve) allows remote attackers to execute arbitrary code via Code Injection in the `where` parameter.

This bug has been fixed in version 0.7.5!
