### ISSUE TITLE
Error from deploying Eve application to Apache server with mod-WSGI

### ISSUE THREAD

**Issue by abchang1** [pyeve/eve#1107]
I created a simple application as shown below using Eve v0.7.6, and deployed to Apache server with mod-WSGI.

   from eve import Eve
   app = Eve()
  @app.route('/hello')
  def hello_world():
    return 'Hello World!'
 if __name__ == '__main__':
    app.run()

However, the following error message is logged at the server side when the hello endpoint was accessed.  (Deploying the same application developed using Flask works.)
Please look into this issue.  

![image](https://user-images.githubusercontent.com/35738240/35762276-24d370a2-0862-11e8-95c0-65f7f9dfc2b8.png)

**Comment by nicolaiarocci** [comment]
This looks like a deployment problem. Maybe take a look here http://flask.pocoo.org/docs/0.12/deploying/mod_wsgi/

Please don't use the eve ticket system for stuff not related to eve itself (bugs, features, etc.)

**Comment by abchang1** [comment]
The path of settings.py should be provided: 
app = Eve(settings='/var/www/html/query-app/settings.py')
