### ISSUE TITLE
versioning won't work with compound unique mongo_indexes 

### ISSUE THREAD

**Issue by demonbob** [pyeve/eve#1116]
Hi guys, 

I have a resource named groups, with name, environment as the schema variables. I have a compound index set with name: 1, environment: 1, unique: true on the resource. The compound unqiue index breaks versioning for the groups_versions collection. 

Is their a way to turn off indexes on the versions collection so versioning works?

**Comment by TamiasSibiricus** [comment]
Same problem here. I can't disable unique indexes on some collections. App logic require to handle documents unnique by set of fields. 
Maybe there possible to drop unique to False when versioned collections recreating?
