### ISSUE TITLE
Docs: clear separation between stable and development versions

### ISSUE THREAD

**Issue by thomasleveil** [pyeve/eve#1119]
currently http://python-eve.org/ is the documentation for eve v0.8, which is not the latest stable (0.7.2) and which is not available on pypi.

It took me some time to realize I was reading the documentation for the dev version.

Is the documentation for previous versions (or at least the current stable version) hosted somewhere?

**Comment by cellerich** [comment]
Hi Thomas

It's stated on the first page a little further down:

![image](https://user-images.githubusercontent.com/13665468/37094580-9a6d1816-2213-11e8-9092-6f42e507da27.png)

Dok of stable version is here 
[Link to V0.7.2 Dok](http://eve.readthedocs.org/en/stable/)

**Comment by thomasleveil** [comment]
Thank you cellerich. May I suggest to repeat this information at the top (and even maybe in the side menu)?

maybe something like:

![image](https://user-images.githubusercontent.com/42300/37097691-63f6fa8c-221c-11e8-8266-2794eadf7aa6.png)

**Comment by cellerich** [comment]
Salu Thomas

I'm not the maintainer of the repo or doc, just browsed by and was about to read the documentation myself when I saw your question. Thought I might help a fellow coder :smile: 

Hopefully one of the owners will see your suggestion.

**Comment by nicolaiarocci** [comment]
Good point. Actually I have been planning a major overhaul of the documentation, but never got around to start working on it (side note: reason I started a funding campaign for the project was to hopefully allow me more time to work on the documentation improvement!)

**Comment by nicolaiarocci** [comment]
Done!
