### ISSUE TITLE
TypeError argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by b3g00d** [pyeve/eve#1120]
I using embedded with 3 level depth. Example:
`embedded=='{"item_lines": 1, "item_lines.charge": 1, "item_lines.charge.line_usage": 1}'`.
But the result was return an exception
```
lib/python2.7/site-packages/eve/methods/common.py", line 789, in resolve_embedded_documents
    if last_field not in subdocument:
TypeError: argument of type 'NoneType' is not iterable
```

I tried to bypass like this and result comeout.
```
        for subdocument in subdocuments(fields_chain[:-1], resource, document):
            if not subdocument:
                continue
            if last_field not in subdocument:
                continue
            if isinstance(subdocument[last_field], list):
                subdocument[last_field] = list(map(getter,
                                                   subdocument[last_field]))
            else:
                subdocument[last_field] = getter(subdocument[last_field])
```
Current Eve==0.7.6

Notes:
Some item_lines.charge has been soft deleted

**Comment by nicolaiarocci** [comment]
> Some item_lines.charge has been soft deleted

That's probably what triggers the exception. Thanks for reporting. Feel free to submit a fix, I'll gladly review it.

**Comment by rohanraj7316** [comment]
Hi,
can I take this issue?

**Comment by nicolaiarocci** [comment]
Of course.

**Comment by nicolaiarocci** [comment]
@rohanraj7316 are you still on this?

**Comment by rohanraj7316** [comment]
@nicolaiarocci yes

**Comment by jlismore** [comment]
For anyone with this issue, the below code resolved it for us
```
for subdocument in subdocuments(fields_chain[:-1], resource, document):
            if not subdocument or last_field not in subdocument:
                continue
            subdocument[last_field] = getter(subdocument[last_field])
```

**Comment by nicolaiarocci** [comment]
I pushed a [new branch](https://github.com/pyeve/eve/tree/TypeError_argument_of_type_NoneType_is_not_iterable_%231120). Commit 3937c126f33fa5a426af985cf4d33550a4544108 should fix the issue at hand. 

@b3g00d and @jlismore, can you please test it and let me know if it solves the problem for you? I am having a hard time coding a test for this scenario 😊

**Comment by b3g00d** [comment]
Sorry guys, I have no experience about contributing on GitHub, let me follow the issue, and I will test it in a short time.
