### ISSUE TITLE
AutoIndex for eve ?

### ISSUE THREAD

**Issue by alirezaimi** [pyeve/eve#1121]
How can i show current directory content like index page of httpserver, like AutoIndex module of flask ?
Is there any option like AutoIndex for eve to do this ?

**Comment by nicolaiarocci** [comment]
Well, Flask-AutoIndex should be usable with an Eve app. Have you tried it? If you are looking for a endpoint map, then [Eve-Swagger](http://github.com/pyeve/eve-swagger) is the app extension you are probably looking for.
