### ISSUE TITLE
VALIDATE_FILTERS setting doesn't work for filter on sub-document field

### ISSUE THREAD

**Issue by lmoretto** [pyeve/eve#1123]
Activating the `VALIDATE_FILTERS` setting causes request with filters on sub-documents' fields to fail.

**Steps to reproduce**
Suppose you have a domain resource with the following schema:
```python
'collection': {
    'schema': {
        'sub_documents': {
            'type': 'list',
            'schema': {
                'type': 'dict',
                'schema' : {
                    'foo': {'type': 'string'}
                    'bar': {'type': 'integer'}
                }
            }
        }
    }
}
```
Performing a request like:
`http://<api_server>/collection?where={"sub_documents.bar": 5}`
returns the following response:
```json
{
    "_status": "ERR",
    "_error": {
        "code": 400,
        "message": "filter on '%s' is invalid"
    }
}
```

This seems to be caused in `eve/utils.py` at lines 403-406:
```python
if config.VALIDATE_FILTERS:
    res_schema = config.DOMAIN[resource]['schema']
    if key not in res_schema:
        return "filter on '%s' is invalid"
```
In this scenario, `key` will be `sub_documents.bar` which is not a valid key in the `res_schema` dict (whereas `sub_documents` is).

**Comment by nicolaiarocci** [comment]
Excellent. Looks like we're missing support for sub-document parsing here. Feel free to submit a PR if so inclined, I will gladly review it.
