### ISSUE TITLE
404 unless SERVER_NAME = None

### ISSUE THREAD

**Issue by fhucho** [pyeve/eve#113]
When I start with the minimal application it works fine. When I modify it to make it accessible from outside, I start getting 404 error on http://localhost/.

run.py:

```
if __name__ == '__main__':
    app = Eve()
    app.run(host='0.0.0.0', port=80)
```

settings.py

```
SERVER_NAME = '0.0.0.0:80'
DOMAIN = {'people': {}}
```

I have to set `SERVER_NAME = None` to make it work.

**Comment by johnsanthosh** [comment]
@ronhanson Your comment ''SERVER_NAME = None" saved my day :)
