### ISSUE TITLE
Option to preserve MongoDB key order in JSON response

### ISSUE THREAD

**Issue by abchang1** [pyeve/eve#1131]
Is there currently a way to preserve the key order of documents retrieved from MongoDB? For collections, I am able to use on_fetch event hooks to modify the '_items' collection (by reassigning each item to an OrderedDict), but I cannot achieve this for requesting specific items, i.e. the URL pattern /{collection_name}/{mongo_object_id}. I tried to reassign the response object to an OrderedDict, but this change does not take effect. If there isn't a way to do this currently, could this please be an option? For my application, a specific key order is helpful for document readability.

**Comment by sphet** [comment]
I'm not sure if this solves your order but you can disable sorting on the endpoint or globally:
http://python-eve.org/features.html#sorting

I do this on some endpoints where the sorting was a performance problem.

**Comment by nicolaiarocci** [comment]
I have not tried it, but even for single documents, this should be achievable by leveraging the `on_fetched_item` hook. Have you checked into it? See http://python-eve.org/features.html#eventhooks
