### ISSUE TITLE
array membership test not working as expected

### ISSUE THREAD

**Issue by cbrinley219** [pyeve/eve#1132]
Hi,
I have simple database setup which contains many documents similar to:
```
{
  "_id": "custom.id.format",
  "description": "dev static content",
  "hostname": "devapache1.example.com",
  "name": "apache 1",
  "osName": "Linux",
  "project": "ecom-dev",
  "tags": [
    "so-new",
    "apache",
    "ecom",
    "test"
  ],
  "username": "cfgmgt",
}
```
I am trying to find any document that matches this mongoDB query:
`{"tags": {$in:["so-new"]}}`

using MongoDB Compass the above query returns results as expected, however using ***Eve*** `where` clause like so: 
`curl -v -g 'http://127.0.0.1:5000/inventory?where={"tags": {$in:["so-new"]}}'`

I get the following error: 
```
<p>Error code 400.
<p>Message: Bad request syntax ('GET /inventory?where={"tags": {$in:["so-new"]}} HTTP/1.1').
<p>Error code explanation: 400 = Bad request syntax or unsupported method.
```

Flask request log shows the following:
```
127.0.0.1 - - [07/Apr/2018 12:55:30] code 400, message Bad request syntax ('GET /inventory?where={"tags": {"$in": ["so-new"]}} HTTP/1.1')
127.0.0.1 - - [07/Apr/2018 12:55:30] "GET /inventory?where={"tags": {"$in": ["so-new"]}} HTTP/1.1" 400 -
```

Other where clauses such as matching hostname seem to work fine. Is `$in` supported and if so am I using it correctly for ***Eve*** ? 

Thanks

**Comment by nicolaiarocci** [comment]
Try this:

    curl -G "http://localhost:5000/inventory" --data-urlencode "?where={"tags": {"$in":["so-new"]}}"

**Comment by cbrinley219** [comment]
Thanks that got me a bit further. New error means progress :)
That query returns the entire collection via curl yet in Compass it only returns 2 records of ~1500, but still thats something I can trace out. I'll post anything valuable back

**Comment by cbrinley219** [comment]
heh nothing valuable, just a shell quoting issue :/
this:  `--data-urlencode '?where={"tags": {"$in":["so-new"]}}'`
not this: `--data-urlencode ` *"*`?where={"tags": {"$in":["so-new"]}}`*"*

thanks again for your help

**Comment by nicolaiarocci** [comment]
Ah, right. I edited the original answer so others coming here in the future will have a easier life :-)
