### ISSUE TITLE
New release...?

### ISSUE THREAD

**Issue by stratosgear** [pyeve/eve#1133]
May I, very politely, ask when is the next release coming...?

I'm getting dependency issues with the `werkzeug<=0.11.15` and I would like to upgrade if possible.

Thanks!

**Comment by nicolaiarocci** [comment]
Hello! I am hoping to release v0.8 within this month. Now that Cerberus 1.2 is out I think almost everything is ready.

**Comment by zhangtemplar** [comment]
I do it manual update as `pip install git+https://github.com/pyeve/eve/archive/master.zip` to use the latest code, as I need to use the bits operator.

**Comment by huandzh** [comment]
any updates ? 

i am looking forward to this release as well (need OPLOG fix, projection, etc.)

thx!

**Comment by nicolaiarocci** [comment]
Howdy, everyone, we are feature complete for v0.8. Should be a matter of day now. Hang in there!

**Comment by nicolaiarocci** [comment]
Eve v0.8 has been released.

- PyPI: https://pypi.org/project/Eve/
- Changelog: http://python-eve.org/changelog.html
