### ISSUE TITLE
aggregate query replacement does not handle arrays

### ISSUE THREAD

**Issue by sphet** [pyeve/eve#1134]
Consider the following query:

http://testserver.com/api/averages/?aggregate{ $name":"teapot"}

And the following aggregate on the endpoint:

```
pipeline=[
  // ... more
  {
    '$group' : {    '_id' : { 
       // ... more fields
       debug_name' : '$name' }, 
       'avg' : { '$avg' : { '$arrayElemAt': ['$name',0] }  },
       'min' : { '$min' : { '$arrayElemAt': ['$name',1] }  },
       'max' : { '$max' : { '$arrayElemAt': ['$name',2] }  },
     }
}
]
```

debug_name will be correctly replaced, but $name in the avg, min and max will not.

The parsing code in get.py only considers nesting via dicts, not arrays.

It would be great to fix this as I have no other solution

**Comment by zhangtemplar** [comment]
I would suggest either you use four different variables for `$name`.

Or you could create a pull request and implement your own solutions.

**Comment by sphet** [comment]
I think this is fixed? Can it be closed?
