### ISSUE TITLE
Why are curly brackets not escaped in URL queries?

### ISSUE THREAD

**Issue by alexanderwallin** [pyeve/eve#1153]
Hi there,

I started setting up a few Eve API endpoints in my API debugger client [Insomnia](https://insomnia.rest/), and hit a snag with the URL query formats that Eve expects:

```sh
http://api.url/search?aggregate={%22\$key%22:%22value%22}
```

This is not possible to achieve in Insomnia, because it simply escapes everything, which is kind of what I would expect from an API client as well as from a REST API. The [RFC 1738 has this to say](https://tools.ietf.org/html/rfc1738) about curly brackets and other special characters:

> Unsafe:
>
> Characters can be unsafe for a number of reasons.  The space character is unsafe because significant spaces may disappear and insignificant spaces may be introduced when URLs are transcribed or typeset or subjected to the treatment of word-processing programs. The characters "<" and ">" are unsafe because they are used as the delimiters around URLs in free text; the quote mark (""") is used to delimit URLs in some systems.  The character "#" is unsafe and should always be encoded because it is used in World Wide Web and in other systems to delimit a URL from a fragment/anchor identifier that might follow it.  The character "%" is unsafe because it is used for encodings of other characters.  **Other characters are unsafe because gateways and other transport agents are known to sometimes modify such characters. These characters are "{", "}", "|", "\", "^", "~", "[", "]", and "`".**
> 
> **All unsafe characters must always be encoded within a URL.** For example, the character "#" must be encoded within URLs even in systems that do not normally deal with fragment or anchor identifiers, so that if the URL is copied into another system that does use them, it will not be necessary to change the URL encoding.

Is there a reason curly brackets are not escaped?

All the best,
Alexander

**Comment by nicolaiarocci** [comment]
I am not sure why you need to escape your requests. Insomnia will do that for you (like Postman and all the other clients I'm aware of). I just tried Insomnia locally, and it appears to work just fine:

<img width="1439" alt="screen shot 2018-05-25 at 10 43 09" src="https://user-images.githubusercontent.com/512968/40535108-744b976a-6008-11e8-98c9-db317c007f1b.png">

**Comment by alexanderwallin** [comment]
Thanks for getting back, @nicolaiarocci. I realise I was looking at unofficial documentation. Sorry about that!
