### ISSUE TITLE
http://127.0.0.1:5000/people is not working (following the quickstart)

### ISSUE THREAD

**Issue by bigoper** [pyeve/eve#1160]
I'm followings the docs
- http://python-eve.org/quickstart.html

### Expected Behavior
$ python run.py
 * Running on http://127.0.0.1:5000/people

### Actual Behavior
Nothing gets printed. no output in the console (or web).
The browser is 'loading'...

### Environment

* OS: Mac
* Python version: 3.6
* Eve version: latest

**Comment by nicolaiarocci** [comment]
Is mongod running? You still need the mongo server, as mentioned in the pre-requisites.

**Comment by bigoper** [comment]
Worked like a charm!
Thank you.
