### ISSUE TITLE
Use Flask-PyMongo 2.0

### ISSUE THREAD

**Issue by dcrosta** [pyeve/eve#1166]
Hi there 👋 I'm the author of [Flask-PyMongo](https://github.com/dcrosta/flask-pymongo).

I see that about a year ago Flask-PyMongo was removed as a dependency, and vendored instead. I'm sorry that it was in such disrepair for so long, but I'm reinvigorating it now, and I'd love to help do what I can to make sure that eve uses the new version, receives updates & support, and so on.

Flask-PyMongo 2.0 is currently in beta and should be released some time in early July. There's a moderately long thread on the differences in https://github.com/dcrosta/flask-pymongo/issues/110, but the gist is that it supports configuration by MongoDB URI only, and delegates most of the configuration handling to PyMongo itself, so the sorts of errors reported in #855 should now not be an issue any more.

Please let me know how I can help here, if at all.

Thanks!

**Comment by nicolaiarocci** [comment]
Hello there! It is good to know that Flask-PyMongo is back on track. I am going to be traveling next month or so, but I definitely want to check it out soon. Oh and thanks for reaching out, I really appreciate it.

**Comment by dcrosta** [comment]
Cool -- look forward to hearing back from you here. Thanks!
