### ISSUE TITLE
Support Different Rate Limits for Unauthenticated Users

### ISSUE THREAD

**Issue by ndmeiri** [pyeve/eve#1167]
This is a feature request for the ability to specify different rate limits for unauthenticated users.

The rate limit settings available on the [configuration](http://python-eve.org/config.html) page (`RATE_LIMIT_GET `, `RATE_LIMIT_POST `, etc. ) suggest that rate limits can differ only per endpoint. The [documentation about rate limiting](http://python-eve.org/features.html#rate-limiting) says
> You can set different limits for each one of the supported methods (GET, POST, PATCH, DELETE).

but makes no mention of unauthenticated users. So I don't believe this is currently possible.

It would be useful if rate limits could distinguish between authenticated and unauthenticated users. How difficult would it be to implement this feature?

<hr>

In case the feature needs clarification, I'm imagining having the ability to specify rate limit rules similar to [GitHub's](https://developer.github.com/v3/#rate-limiting) with respect to unauthenticated users:

> [Authenticated requests] can make up to 5000 requests per hour. Authenticated requests are associated with the authenticated user, regardless of whether Basic Authentication or an OAuth token was used.
> [...]
> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

**Comment by ndmeiri** [comment]
@nicolaiarocci, first of all, thanks for the awesome framework! 
I'd be happy to try to help. I've used Eve for a few months, but I haven't dug too deep into the internal code. Plus I'm pretty swamped with other things at the moment, so I'm not sure what my time commitment could be.

Anyway, I'd like to discuss the scope of this feature. In addition to unauthenticated users, some Eve users may want to specify different rate limits for different roles (e.g., an `admin` role ignores rate limits while a normal `user` role is limited to X requests per hour.) How general do you want to make this feature?

**Comment by nicolaiarocci** [comment]
I'd keep it simple. Allow setting of different limits for authenticated and unauthenticated users.

**Comment by mostafazh** [comment]
@nicolaiarocci @ndmeiri would you want to add `RATE_LIMIT_UNAUTH_GET`, `RATE_LIMIT_UNAUTH_POST`, `RATE_LIMIT_UNAUTH_PATCH` and `RATE_LIMIT_UNAUTH_DELETE`? 

What if one is not defined? I guess it should default to the `RATE_LIMIT_<method>` (if doesn't exist then it should be `None`)
