### ISSUE TITLE
Support for additional REST API output formats

### ISSUE THREAD

**Issue by danielopitz** [pyeve/eve#1169]
I'm interested in getting JSON API support into Eve and would like to contribute my time for the implementation. It would be nice to make the response formatting more general to allow adding different outputs.

So there are two ways I can think about regarding the implementation:
1. Either leave additional formats to plug-ins 
2. Add additional formats to the core

Both ways would need some refactoring to decouple the HATEOAS from the rest (pun not intended) of the response code.

Any ideas / suggestions / discussion points? I would be glad for some starting hints too.

**Comment by nicolaiarocci** [comment]
Hi, I'd like to see this happen as well. Going the plug-ins/extensions route would probably be a good idea, just like we did with data-layers. Agree that HATEOAS needs refactoring, something I've been wanting to do for a long time. Feel free to work on this!

**Comment by danielopitz** [comment]
Thanks, I'll look into it when I'm back from vacation.
