### ISSUE TITLE
Database projection not working

### ISSUE THREAD

**Issue by mrigesh** [pyeve/eve#1171]
### Expected Behavior

```
resource={
    "datasource":{
        "projection":{
            "a.b.c":0
        }
    }
}

the following should remove "c" in the final response 
```

### Actual Behavior

"c" as stated above isn't removed and is still visible in response

### Environment

* Python version: 3.6.5
* Eve version: 0.8.0
* Was working with eve 0.7.8

**Comment by nicolaiarocci** [comment]
be aware that the behavior has changed with v0.8, see https://github.com/huandzh/eve/pull/2 for a full reference. If you still feel that an issue is about, please let me know or, even better, PR a fix. Thanks.

**Comment by nicolaiarocci** [comment]
Updated docs at http://python-eve.org/config.html#limiting-the-fieldset-exposed-by-the-api-endpoint
