### ISSUE TITLE
Soft delete removes auth_field from document

### ISSUE THREAD

**Issue by gwainer** [pyeve/eve#1188]
### Expected Behavior

When using soft delete, the deleted document should remain with auth_field after deleted. I've tested using eve 0.7 and this is true, but I've noticed using eve 0.8 that with soft delete enabled, when a document is deleted, its auth_field is removed. 

I see [here](https://github.com/pyeve/eve/blob/v0.8/eve/methods/delete.py#L86), inside eve's `deleteitem` function, the document is retrieved from database with `force_auth_field_projection` with default value False, and then [here](https://github.com/pyeve/eve/blob/v0.8/eve/methods/delete.py#L113) this document without `auth_field` replaces the original. 

That's undesired in my case because I need to keep the deleted documents belonging to the user that owns it. So later when getting the deleted documents I can bring the ones he deleted, and losing the auth_field this is not possible, the document ends ups inaccessible since it has no auth_field but the schema uses it.

### Environment
* Python version: 3.5.1
* Eve version: 0.8

Thanks,

**Comment by nicolaiarocci** [comment]
it took a while, but it should be fixed now.

**Comment by gwainer** [comment]
Thank you! Any idea when 0.8.2 will be released?

**Comment by nicolaiarocci** [comment]
Targeting next month!
