### ISSUE TITLE
Unable to set `allow_unknown` on `app.validator` during initialization

### ISSUE THREAD

**Issue by jsolbrig** [pyeve/eve#1190]
### Disclaimer

This may be a misunderstanding on my part, but it appears to be a bug.  Performing the same action directly with `cerberus.Validator` appears to work fine, but when initializing from `app.validator` it does not.  Also, if the `resource` keyword is not set, this works correctly.

### Expected Behavior

After initialization with `allow_unknown=True`, `allow_unknown` should be set to `True` on `cerberus.Validator` instance.

```python

# Works without a resource set
>>> validator = app.validator({}, allow_unknown=True)
>>> print(validator.allow_unknown)
True

# Fails with a resource set
>>> validator = app.validator({}, resource='test', allow_unknown=True)
>>> print(validator.allow_unknown)
False
```

### Actual Behavior

`allow_unknown` is set to false on the resulting object.

### Environment

* Python version: 3.6.6
* Eve version: 0.8.1

**Comment by nicolaiarocci** [comment]
hello, Is `app.validator` the built-in mongo validator, or a custom one?
