### ISSUE TITLE
Add GitHub metadata and documentation link to PyPI

### ISSUE THREAD

**Issue by nicolaiarocci** [pyeve/eve#1200]
For reference, take a look at [Flask page on PyPI](http://docs.python-eve.org/en/latest/changelog.html)

<img width="297" alt="image" src="https://user-images.githubusercontent.com/512968/46522611-8e642980-c883-11e8-9532-11162d773b98.png">

**Comment by nicolaiarocci** [comment]
`project_urls` [was supposed to do the trick](https://github.com/pyeve/eve/blob/master/setup.py#L36), but somehow PyPI did not pick it up. Investigate further.

**Comment by pedro2555** [comment]
For sure isn't that missing. Maybe you need that if the `url` field isn't where the code is, but just I guess of mine.

I have small project on pypi, it shows stats from GitHub, and has none of that on the `setup.py` file.

One thing I noticed is the project is name `eve` on GitHub and `Eve` on pypi, maybe that is the issue?

**Comment by nicolaiarocci** [comment]
![image](https://user-images.githubusercontent.com/512968/55944582-31d63280-5c49-11e9-802d-15d6457102cb.png)
