### ISSUE TITLE
DeprecationWarning on newer pymongo

### ISSUE THREAD

**Issue by nicolaiarocci** [pyeve/eve#1202]
`DeprecationWarning: count is deprecated. Use Collection.count_documents instead.` is returned by pymongo 3.7.2. Consider updating the code to silence the warning, and of course pin to pymongo 3.7+

**Comment by einarhuseby** [comment]
@nicolaiarocci - I was looking into this and soon found that
```
cursor = app.data.find(resource, req, lookup)
count = cursor.count()
```
needs to be replaced like
```
count = collection.count_documents({"foo": "bar"})
```
For Eve I think either a new `count` method for the datalayer `count = app.data.count(resource, req, lookup)` or handle it in  `find` and change the return signature from `cursor` to `count, cursor`.

Both will break the current base datalayer. Personally I favor the latter. What are your thoughts on this?

Also pymongo 3.7 added [estimated_document_count]( http://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.estimated_document_count). See also this [SO answer](https://stackoverflow.com/questions/52236594/why-is-pymongo-count-documents-is-slower-than-count)

This could possible be of use;  `OPTIMIZE_PAGINATION_FOR_SPEED` could be replaced with something like `PAGINATION_STRATEGY` and a corresponding resource override `pagination_strategy` with options full count, estimated count and no count.

I could provide a PR to see how it pans out.

**Comment by nicolaiarocci** [comment]
> I could provide a PR to see how it pans out.

Please do.
