### ISSUE TITLE
Backend DB different than Mongo?

### ISSUE THREAD

**Issue by mrkafk** [pyeve/eve#1203]
MongoDB (at least some parts of it) is Affero GPL-licensed, which triggers immediate ban in many companies, including but not limited to mine, due to inherent legal risks and legal flaws present in Affero GPL.

I cannot use Mongo where I work under any circumstances (well apart from buying commercial Mongo which on the other hand is deemed too expensive). 

Is it possible to plug in some other NoSQL / JSON db into pyeve? Say, something like RethinkDB that is released under friendly Apache license? 

If not, would necessary modifications be major in scope and risk?

**Comment by nicolaiarocci** [comment]
if you take the time to look at the [extensions page](http://docs.python-eve.org/en/latest/extensions.html) in the documentation, you'll find that people have beein doing that for years. Community extensions include Eve-SQLAlchemy, Eve-Elastic, Eve-Neo4j. 

You can look at these repositories to get an idea of how it's done. The gist of it, however, is that you need to subclass the [base `DataLayer` class](https://github.com/pyeve/eve/blob/master/eve/io/base.py#L61). That's actually how the mongo implementation is done, too. It just so happens to be the default one.
