### ISSUE TITLE
Settings loading strategy does too much and lead to wrong assumptions

### ISSUE THREAD

**Issue by Annakan** [pyeve/eve#1205]
### Expected Behavior
I expected and the documentation hints has such changing config after loading the setting file is fine, and that if one wants to benefits from the defaults one needs to load them from a file.
But that's not true because propagation of global settings to the domain happens at config file loading time.
And there is no way to tweak the settings before applying them :EveWSGIRequestHandler.load_config` does too much.

```python
# let's suppose that :
# test_settings.py contains a domain "people" with no settings
# related to sorting, embedding, no global settings
settings_file = os.path.join(self.this_directory, 'test_settings.py')
app = eve.Eve(settings=settings_file)
```
then
`app.config['people']['sorting'] = True # the default value`

now do
```
app.config['SORTING']=False
# and then and wrongly
config['people']['sorting'] is True 
# still default value because values have been propagated at loading
```

The documentation wrongly states that besides loading default values for settings, it is the same to pass a dict, a file or to change settings afterwards, but it is not.

May I suggest that  `EveWSGIRequestHandler.load_config` becomes a class method that simply returns a dict and that default values should be applied **afterwards** to the domains, in __init__ or some other helper method ?

The current behavior could be preserved by accepting a file name as now, and loading the config and applying default as now but through the class method.
All the while passing a dictionary would also benefit from defaults where they are not provided 
and more importantly **this* would be doable :

`eve_config = EVE.load_config() # default config`
 or
 `eve_config = EVE.load_config("my_setting.py) # same with my_settings.py settings applied`

and then

```eve_config['SORTING']=False``` (because a command line parameter is overriding, or for testing reasons)

before doing

```app = Eve(settings=eve_config)```

And the documentation could be corrected stating that it is wrong to change propagable values after __init__ (or we would need to check them dynamically :+1: 
 
`if not config.get(setting_name) then config.get(setting_name.upper())`

**Comment by nicolaiarocci** [comment]
Hi,

This is more or less in line with the work I planned to do in light of a future CLI client. Things slowed down, mostly because of the unsuccessful funding campaign which was basically thought to buy me time to work the next level of the whole eve ecosystem. 

Short version: I like your proposal. Please feel free to submit a PR if you feel so inclined.
