### ISSUE TITLE
Controlling pagination over large collections

### ISSUE THREAD

**Issue by checkaayush** [pyeve/eve#1211]
@nicolaiarocci Could you help me understand how the default pagination works? 

Is it the standard limit + skip based pagination? If so, this strategy is known to be less performant over large collections after a good number of iterations. Is there a way to extend / change the it? Or should I create a custom endpoint and handler if a different pagination strategy is required.

I've seen the OPTIMIZE_PAGINATION_FOR_SPEED option and understand the count query for every request might become the bottleneck over large collections. 

I have 
### Environment

* Python version: 3.5.2
* Eve version: 0.8.1

P.S.: Loved Eve. :+1: :)

**Comment by nicolaiarocci** [comment]
Hi, the short answer is yes, pagination is not very performant on large collections. If you enable `OPTIMIZE_PAGINATION_FOR_SPEED` it will perform better:

> Set this to True to improve pagination performance. When optimization is active no count operation, which can be slow on large collections, is performed on the database. This does have a few consequences. Firstly, no document count is returned. Secondly, HATEOAS is less accurate: no last page link is available, and next page link is always included, even on last page. On big collections, switching this feature on can greatly improve performance. Defaults to False (slower performance; document count included; accurate HATEOAS).

Things might improve when I get a chance to look at PyMongo 3.7 support for `estimated_document_count`.
