### ISSUE TITLE
Demo fails

### ISSUE THREAD

**Issue by SuperHighMan** [pyeve/eve#1222]
QuickStart:
root@xtgl-app-009:/root/a#cat run.py 
from eve import Eve
app = Eve()
app.run()
root@xtgl-app-009:/root/a#cat settings.py 
DOMAIN = {'people': {}}
root@xtgl-app-009:/root/a#
--------------------------------------------------------------------------------------
Then I run the demo:
root@xtgl-app-009:/root/a#python3 run.py 
 * Serving Flask app "eve" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
--------------------------------------------------------------------------------------
Then I follow the guide:
root@xtgl-app-009:/root/a#curl -i http://127.0.0.1:5000/people
curl: (52) Empty reply from server
root@xtgl-app-009:/root/a#curl -i http://127.0.0.1:5000/
curl: (52) Empty reply from server
-----------------------------------------------------------------------------------
Finally, I have no idea.  SO How to deal with it ?

**Comment by wangleisldt** [comment]
root@xtgl-app-009:/root/a#mongo 127.0.0.1:27017 -u "cmdb" -p "xtwh8wl8" --authenticationDatabase "cmdb"
MongoDB shell version v3.6.9
connecting to: mongodb://127.0.0.1:27017/test
Implicit session: session { "id" : UUID("0cda752f-0d5e-4982-8f68-d31fa9ebf039") }
MongoDB server version: 3.6.9
MongoDB Enterprise > exit
bye

################################################################


root@xtgl-app-009:/root/a#
root@xtgl-app-009:/root/a#
root@xtgl-app-009:/root/a#cat run.py
from eve import Eve
from flask import current_app as app


config = {
    'MONGO_HOST': '127.0.0.1',
    'MONGO_PORT': 27017,
    'MONGO_DBNAME': 'cmdb',
    'MONGO_USERNAME': 'cmdb',
    'MONGO_PASSWORD': 'xtwh8wl8',
    'DEBUG': True,
    'DOMAIN': {'people': {}}
}


app = Eve(settings=config)
app.run()


###############################################################
root@xtgl-app-009:/root/a#
root@xtgl-app-009:/root/a#
root@xtgl-app-009:/root/a#python3 run.py
 * Serving Flask app "eve" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 179-815-898

###############################################################

root@xtgl-app-009:/root#curl -i http://127.0.0.1:5000/
curl: (52) Empty reply from server
root@xtgl-app-009:/root#curl -i http://127.0.0.1:5000/people/
curl: (52) Empty reply from server
root@xtgl-app-009:/root#
