### ISSUE TITLE
Expecting JSON response for rate limit exceeded scenario

### ISSUE THREAD

**Issue by checkaayush** [pyeve/eve#1227]
### Expected Behavior

A JSON response should be returned:

```json
{
  "_status": "ERR",
  "_error": {
    "code": 429,
    "message": "Rate Limit exceeded"
  }
}
```
### Actual Behavior

Text message saying _Rate limit exceeded_ is returned with the code 429.

Refer: https://github.com/pyeve/eve/blob/master/eve/methods/common.py#L312

### Environment

* Python version: 3.5.x
* Eve version: 0.8.1

**Comment by checkaayush** [comment]
Would be happy to submit a PR if JSON response was the expected behavior. If not, is there any advantage in sending a text response instead?

**Comment by nicolaiarocci** [comment]
Yes please, do submit a PR for this. I will gladly review it.

**Comment by checkaayush** [comment]
Here you go https://github.com/pyeve/eve/pull/1236 :)
