### ISSUE TITLE
Duplicate version argument in HATEOAS links

### ISSUE THREAD

**Issue by kallqvist** [pyeve/eve#1233]
Hey, thanks for a great project!

I've just noticed that I get duplicate arguments in the returned self-link when using ?versions on an item endpoint.
I am not sure if ?versions is the only argument acting like this but I do know that it does not happen with for instance ?where.

### Expected Behavior
URL return as HATEOAS link should semantically match the actual input arguments and never have duplicated arguments (unless perhaps if the input also contains duplicates...)

### Actual Behavior
One extra version=diffs gets added to URL's.
If this new URL is sent back to Eve the next response will have added a third version=diffs.

![Screenshot from 2019-03-12 16-52-04](https://user-images.githubusercontent.com/937404/54214845-4064e900-44e7-11e9-82d8-21136cb93f11.png)

### Environment

* Python version: Python 3.6.7
* Eve version: 0.8.1

**Comment by nicolaiarocci** [comment]
Hello, 

Should be fixed in v0.8.2, see https://github.com/pyeve/eve/pull/1228
