### ISSUE TITLE
List of dictionaries

### ISSUE THREAD

**Issue by Shatten** [pyeve/eve#1237]
### Expected Behavior

Hello
Discovered such a feature

Created a field list without specifying the scheme

```python
'test_list': {
    'type': 'list',
},
```

Request from the browser I get

```xml
<test_list>
    <test> test1 </test>
</test_list>
<test_list>
    <test2> test1 </test>
</test_list>
```

But the database has a list of dictionaries.
Also in the code I get a list of dictionaries.

The question is, is it a bug or a feature?
```python
eve_server.add_object({'test_list': [{'test':'test1'}, {'test2':'test1'}]})
```

### Environment

* Python version: 3.6
* Eve version: 0.8.1

**Comment by nicolaiarocci** [comment]
what do you get if you ask for JSON? I suspect that's how XML renders a dictionary (but did not check really)
