### ISSUE TITLE
Support CRUD operations on schema endpoint

### ISSUE THREAD

**Issue by smeng9** [pyeve/eve#1249]
Hi @nicolaiarocci,
I am working on a CMS project that uses [React-admin](https://marmelab.com/react-admin/) as front end and PyEve as back end. One use case is: the user needs to customize schemas from the front end instead of modifying settings.py then restart to reload the new schemas.

Currently, all schema are predefined statically in settings.py and the schema endpoint is read-only. The following suggested feature will allow users to create and modify schema dynamically in a RESTful way. This feature may be similar to the one proposed in #1118.

The necessary modification for this feature will include:

1. Provide an option in settings.py to store schema definitions in a separate MongoDB collection
2. Allow (authenticated) user to perform create/update/delete operations on schema endpoint
3. Use (cerebrus) validator to validate the schema
4. Automatically register the schema changes to PyEve without the need to restart it
5. Listen to changes on the schema definitions collection in MongoDB and reload the schema to PyEve. (If we have many replicas of PyEve instances running and needs to keep their schema definitions consistent)

**Comment by nicolaiarocci** [comment]
Hi,

This would be quite a large feature. Are you volunteering for implementing and maintaining it in the long run? I am hesitant to add new big features at this point so it is important that they are backed by interested parties in the long run.

**Comment by nicolaiarocci** [comment]
I also wonder how useful would be to the community at a large, seems quite a niche use-case to me, but I might be wrong of course. So if anyone would be interested, please add your support.

**Comment by smeng9** [comment]
Thank you for the suggestion. I totally agree with your concern that this feature will have a lot of development involved and you want to keep the code maintainable in the long run.

I'm posting here because I also want to see how many people are interested in that feature. All comments are welcomed. I will wait a while before moving on.

As for implementation, I divided this feature into 5 stages in the issue. For the first 2 stages, I may have spare time to start working on them. For the last 3 stages, they are optional and depends how many people are interested in them.

**Comment by cuonglm** [comment]
:+1: I can support implement and maintaining.

**Comment by nicolaiarocci** [comment]
I assume you already know about the [schema endpoint](http://docs.python-eve.org/en/latest/features.html#the-schema-endpoint) feature? Could be a good starting point (it is read-only right now)

**Comment by mingfang** [comment]
This would be a game changing feature. Please re-open
