### ISSUE TITLE
Option to set query_objectid_as_string per query

### ISSUE THREAD

**Issue by luiscoms** [pyeve/eve#1252]
My API has some fields that its type is `string` and its content is a hash that matches `objectid` type, so when I search on API by these fields it returns nothing.
If i set `"query_objectid_as_string": True,`, it returns my records but do not return records by `_id` field.

My suggestion is an option to pass on query that skip this verification on specific field like:

```python
{
    'some-filed': {
        'type': 'string',
        'required': True,
        'empty': False,
        'skip_objectid': True,
    },
}
```

Or even a parameter on query that skip this verification

**Comment by nicolaiarocci** [comment]
Hi, did you try to set `some-field` as a custom type, like `my_not_really_an_objectid_type_of_string`? You can extend the type system supported by Eve (Cerberus), see http://docs.python-eve.org/en/latest/validation.html#extending-data-validation

**Comment by luiscoms** [comment]
The problem is not in validation, it is on query:

https://github.com/pyeve/eve/blob/master/eve/io/mongo/mongo.py#L823

**Comment by nicolaiarocci** [comment]
That line should only be executed [if the type is a string](https://github.com/pyeve/eve/blob/master/eve/io/mongo/mongo.py#L842), though (haven't tried myself)

**Comment by luiscoms** [comment]
This value `"5c8a679a2e5ef3035134a2ea"` is an string, so it will be trigger the cast function

**Comment by nicolaiarocci** [comment]
In your settings, you define your field as a new, custom, type. Let's call it `not_an_objectid`:

    {"some_field": {"type": "not_an_objectid"}}

You define a custom `Validator` class which validates the custom type. Something along the lines of:

    from eve.io.mongo importo Validator

    class Validator(Validator):
        def _validate_type_not_an_objectid(self, value):
            # if needed, validate the value here.
            return True

You pass your custome validator to Eve:

    app = Eve(validator=Validator)
    app.run()

Now if you query on `some_field` it will correctly find it because it is not a string type.

**Comment by luiscoms** [comment]
I have tried this approach and does not work.

It falls on this point when I search by new field, which does not matter the field configuration.

https://github.com/pyeve/eve/blob/master/eve/io/mongo/mongo.py#L843
