### ISSUE TITLE
Improper authorization error when authenticating in eve/auth.py

### ISSUE THREAD

**Issue by checkaayush** [pyeve/eve#1259]
### Expected Behavior

When invalid credentials are supplied for Token based auth, 401 should be thrown as the last exception and that should be there in response message returned. 

### Actual Behavior

```json
{
    "_status": "ERR",
    "_error": {
        "code": 500,
        "message": "__init__() got an unexpected keyword argument 'response'"
    }
}
```
```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/eve/methods/common.py", line 317, in rate_limited
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/eve/auth.py", line 79, in decorated
    return auth.authenticate()
  File "/usr/local/lib/python3.6/site-packages/eve/auth.py", line 270, in authenticate
    abort(401, description="Please provide proper credentials", response=resp)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/exceptions.py", line 752, in abort
    return _aborter(status, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/exceptions.py", line 733, in __call__
    raise self.mapping[code](*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'response'
```

### Environment

* Python version: 3.6
* Eve version: 0.8.1

**Comment by nicolaiarocci** [comment]
I guess you upgraded to werkzeug 0.15.2? They broke backwad compatibility with 0.15.x, try going back to 0.14.1 and see if you solve the issue. Alternatively, you move to v0.8.2-dev of Eve, which supports the new werkzeug amenities ;-)

**Comment by checkaayush** [comment]
I didn't deliberately upgrade to werkzeug 0.15.2. I'd prefer upgrading to v0.8.2-dev of Eve, but there isn't a release for the same, due to which, `pip install`ing is failing. Can you add a pre-release for it or something?

**Comment by nicolaiarocci** [comment]
try installing directly from github `pip install git+https://github.com/pyeve/eve.git`

**Comment by checkaayush** [comment]
Ok. I'm working in a dockerized environment and would have to install git in my base docker image for this to work. 

Alternatively, I've pinned werkzeug's version to 0.14.1 in my requirements.txt and mentioned it before Eve. This has fixed my issue for now. I'll remove the pinning once Eve 0.8.2 is released.

This brings out the importance of fixing or version limiting all dependencies. Interesting project to do the same: https://github.com/pypa/pipenv.

P.S.: Thanks @nicolaiarocci for the prompt reply.

**Comment by nicolaiarocci** [comment]
Actually, we used to pin the dependencies. I think if you browse the old tickets you'll find a long discussion on this very same topic.

**Comment by nicolaiarocci** [comment]
PS: hoping to release 0.8.2 this month
