### ISSUE TITLE
`ValidationError` not found

### ISSUE THREAD

**Issue by rmlopes** [pyeve/eve#1262]
I have not used the framework for some months now. I upgraded the package to latest (0.7.10), and started a new project and got the error message. Eve-demo shows the same error. 

### Expected Behavior

Should run out-of-the-box.

```python
# using eve-demo
```

### Actual Behavior

Throws error. Maybe it is a mismatch with cerberus version?

```pytb
Traceback (most recent call last):
  File "run.py", line 19, in <module>
    from eve import Eve
  File "/usr/local/lib/python3.5/dist-packages/eve/__init__.py", line 87, in <module>
    from eve.flaskapp import Eve  # noqa
  File "/usr/local/lib/python3.5/dist-packages/eve/flaskapp.py", line 24, in <module>
    from eve.endpoints import collections_endpoint, item_endpoint, home_endpoint, \
  File "/usr/local/lib/python3.5/dist-packages/eve/endpoints.py", line 18, in <module>
    from eve.methods import get, getitem, post, patch, delete, deleteitem, put
  File "/usr/local/lib/python3.5/dist-packages/eve/methods/__init__.py", line 15, in <module>
    from eve.methods.post import post
  File "/usr/local/lib/python3.5/dist-packages/eve/methods/post.py", line 19, in <module>
    from eve.validation import ValidationError
  File "/usr/local/lib/python3.5/dist-packages/eve/validation.py", line 16, in <module>
    from cerberus import ValidationError, SchemaError
ImportError: cannot import name 'ValidationError'

```

### Environment

* Python version: 3.5.3
* Eve version: 0.7.10

**Comment by nicolaiarocci** [comment]
Which version of Cerberus are you using?

**Comment by rmlopes** [comment]
Cerberus is the latest, 1.2.

**Comment by nicolaiarocci** [comment]
Well Eve 0.7.x is pinned to to Cerberis 0.9.2, see https://github.com/pyeve/eve/blob/v0.7.9/requirements.txt#L1

Cerberus 1 broke backward compatibility. you want to upgrade to Eve 0.8+ (which also broke backward compatibility) if you want to use latest cerberus. All this info is contained in the eve changelog, look there for details.

**Comment by rmlopes** [comment]
My problem may have been generated with the installation of the SQLAlchemy extension. I did an upgrade before and should have gone to the latest but apparently it did not go as inteneded. I uninstalled and reinstalled and now I am on the latest.

Isee the follwoing warning:

```
eve-sqlalchemy 0.7.0 has requirement Eve<0.8, but you'll have eve 0.9 which is incompatible.

```
