### ISSUE TITLE
Eve document count broken with concurrent requests

### ISSUE THREAD

**Issue by ermescs** [pyeve/eve#1271]
This issue affects Eve when it is executed either on the Flask's development server with the default multi-threaded configuration, or when deployed in a production server such as Gunicorn using an async worker type (e.g. gevent).

### Expected Behavior

For a given GET request, Eve should always return the proper document count in the _meta field, based on the client requested filter.

### Actual Behavior

When performing multiple concurrent GET requests, in the scenario described above, there is a high chance of getting wrong results for the document count.

For instance, consider the following resource:
```json
{
    "_id": 1,
    "value": "a"
},
{
    "_id": 2,
    "value": "a"
},
{
    "_id": 3,
    "value": "b"
}
```
If we perform the following two concurrent requests:
```
1. GET http://server/resource?where={"value": "a"}
2. GET http://server/resource?where={"value": "b"}
```
There is a high change of getting the following wrong results:

```
1.
{
    "_items": [
        {
            "_id": 1,
            "value": "a"
        },
        {
            "_id": 2,
            "value": "a"
        }
    ],
    "_meta": {
        "total": 2
    }
}

2.
{
    "_items": [
        {
            "_id": 3,
            "value": "b"
        }
    ],
    "_meta": {
        "total": 2    <---------------- WRONG!!!!
    }
}
```
or:
```
1.
{
    "_items": [
        {
            "_id": 1,
            "value": "a"
        },
        {
            "_id": 2,
            "value": "a"
        }
    ],
    "_meta": {
        "total": 1    <---------------- WRONG!!!!
    }
}

2.
{
    "_items": [
        {
            "_id": 3,
            "value": "b"
        }
    ],
    "_meta": {
        "total": 1
    }
}
```

This seems to be caused by the changes introduced in 61de6d806ac997954dd3784a2ac13d42c919470a and ac3bd78a9dfcad38e2fe478c0f35f66ac290c37c. With these changes, Eve stores the last used cursor and filter specification in a global object and later uses them to retrieve the document count. This can lead to the above issues when document count is accessed in a concurrent/async way for multiple requests/

### Environment

* Python version: 3.7.0
* Eve version: 0.9
* Flask version: 1.0.2
* Gunicorn version: 19.9.0
* Gevent version: 1.4.0

**Comment by nicolaiarocci** [comment]
hi, which mongodb version are you on?

**Comment by ermescs** [comment]
Hi, I'm using mongodb v4.0.1

**Comment by nicolaiarocci** [comment]
Could you please test if the [this branch](https://github.com/pyeve/eve/tree/issue_%231271) solves the issue for you?

**Comment by ermescs** [comment]
Yes, with the changes in that branch the issue is solved ;)
