### ISSUE TITLE
Eve is using Cerberus functionality that was deprecated in 2017

### ISSUE THREAD

**Issue by sybrenstuvel** [pyeve/eve#1278]
### Expected Behavior

Running the latest version of Eve with the latest version of Cerberus shouldn't raise deprecation warnings, at least not almost two year old deprecation warnings.

### Actual Behavior

Tell us what happens instead.

```
% python -Wd                     
<snipped non-Eve-related deprecation warning>
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from eve import Eve
/path/to/Cerberus-1.3.1-py3.6.egg/cerberus/validator.py:1559:
DeprecationWarning: Methods for type testing are deprecated, use TypeDefinition
and the 'types_mapping'-property of a Validator-instance instead.
```

This warning was introduced in [Cerberus commit ce1ef4f9](https://github.com/pyeve/cerberus/commit/ce1ef4f9ecce7853c903a4eccb4f97a6af16fbb2) in August 2017, almost two years ago.

Our unit testing system unloads & restarts Eve for every test, to ensure test isolation. This means that for every test we get this deprecation warning.

### Environment

* Python version: 3.6.7
* Eve version: 0.9.1

**Comment by sybrenstuvel** [comment]
I'm guessing this is still relevant.

**Comment by sybrenstuvel** [comment]
I'm guessing this is still relevant.

**Comment by luiscoms** [comment]
My tests show same warning

**Comment by sybrenstuvel** [comment]
I'm guessing this is still relevant. We're in the process of moving away from Eve, though, so personally it's not relevant to me any more.

**Comment by sdjmchattie** [comment]
Just for the record, I also see this warning.

**Comment by nicolaiarocci** [comment]
Hi folks. If anybody is willing to work on this item, I'd be more than happy to review their PR!

**Comment by psi29a** [comment]
Tracking this issue too...

**Comment by nicolaiarocci** [comment]
Closing this for the time being. See #1471 for insights.
