### ISSUE TITLE
Ability to disable concurrency check on demand with query param

### ISSUE THREAD

**Issue by arnauorriols** [pyeve/eve#1288]
What do you think about having the capacity to disable concurrency check on a request basis, using a query parameter?

The use case is the following:

I'm building a mirror slave of an Eve API where I replicate all the events that happen on the master, for testing purposes. Data might be post-processed in the slave, resulting in a different etag than the one from the master. The goal is that when some document is created or changed in the master, the data in the slave is overriden.

Currently, I'm being forced to do a HEAD to get the etag (regardless of the document) just to be able to override it. I cannot disable the concurrency check globally, because my application still depends and makes good use of the concurrency checks. Taking into account the "we are consenting adults" mantra of the Python community, I wonder if being able to do `PUT https//eve.app/foo/<id>?force=true` would be a good addition.

**Comment by nicolaiarocci** [comment]
Well, at the very least it should be configurable via config, and disabled by default. Would that be an issue for your use case?

**Comment by arnauorriols** [comment]
No, it wouldn't be an issue.

**Comment by nicolaiarocci** [comment]
I will be happy to review a PR for this.
