### ISSUE TITLE
Error 400 Exception Error Versioning when POST 

### ISSUE THREAD

**Issue by masrayie** [pyeve/eve#1294]
Hi 

I have an issue when doing POST and VERSIONING = True

I always got response error "KeyError : 'collection_versions'"
but my data was saved to database.

When i'm trying to PATCH the data, i got error 400 and message "An exception occurred: 'collection_versions'" but my data was updated.

And all 'versions' collection were not created

But when i set Versioning to False, all is worked.

Could anyone help ?

Thank you

This is my Setting code 
`RESOURCE_METHODS = ['GET', 'POST']

MONGO_QUERY_BLACKLIST = ['$where']

ITEM_METHODS = ['GET', 'PATCH', 'PUT', 'DELETE']

DATE_CREATED = 'created_on'

LAST_UPDATED = 'updated_on'

DATE_FORMAT = "%Y-%m-%d %H:%M:%S"

EXTENDED_MEDIA_INFO = ['content_type', 'name', 'length']

RETURN_MEDIA_AS_URL = True

OPLOG = True

OPLOG_AUDIT = True

PAGINATION = True

RETURN_MEDIA_AS_BASE64_STRING = False

PAGINATION_DEFAULT = 25

VERSIONING = True`

### Environment

* Python version: 3.6
* Eve version: 0.9.2

**Comment by masrayie** [comment]
anyone know this problem ?

**Comment by masrayie** [comment]
anyone can help ?

**Comment by Ziul** [comment]
Getting a similar error.

##### Domain declaration

```
{
    'schema': record_schema,
    'versioning': True,
    'datasource': {
        'source': 'records',
    },
    'mongo_indexes': {
        'author': (
            [
                ('author', 1)
            ]
        )
    }
}
```

##### Schema declaration

```
{
    'title': {'type': 'string', 'required': True, 'empty': False},
    'text': {'type': 'string', 'required': True, 'empty': False},
    'author': {'type': 'objectid', 'default': '', 'coerce': (str, get_user_id)},
}
```

##### Log error

```
[...]
  File "/[...]/lib/python3.6/site-packages/eve/io/base.py", line 357, in datasource
    dsource = config.SOURCES[resource]
KeyError: 'records_versions'
```

**Python-Eve version**: 1.1
**Cerberus version**: 1.3.2
**Pymongo version**: 3.10.1
