### ISSUE TITLE
[DOC] Global Configuration Table could have more than 2 columns

### ISSUE THREAD

**Issue by ambroiseRabier** [pyeve/eve#1300]
https://docs.python-eve.org/en/stable/config.html table could have more than 2 columns, we could add `default` and `type` column (or `allowed values` if you do not like typings).

It would be much more readable.

| Name       | Type                    | Default | Description                                                                                                                          |
| ---------- | ----------------------- | ------- | ------------------------------------------------------------------------------------------------------------------------------------ |
| X_DOMAINS  | Union[None, '*', str[]] | None    | CORS (Cross-Origin Resource Sharing) support. Allows API maintainers to  specify which domains are allowed to perform CORS requests. |

**Comment by nicolaiarocci** [comment]
That would be nice. Feel free to submit a PR for it!

**Comment by ambroiseRabier** [comment]
How can I edit reStructedText simple table efficiently? I have tried https://truben.no/table/ but the output is wrong.
