### ISSUE TITLE
DynamoDB support

### ISSUE THREAD

**Issue by agutoli** [pyeve/eve#1301]
Hi. I am currently working for a serverless project tool and we want to avoid use 24/7 services which is more difficult to optimize costs like create a MongoDB EC2 server (also, we don't want to have one database to maintain), etc.

Do you guys have plans to support AWS DynamoDB?

**Comment by nicolaiarocci** [comment]
No, but we're willing to add community data layer extensions to the project in case you are willing to start work on one. Eve-Elastic is one example of such thing.
