### ISSUE TITLE
Support error code 402 for payment required

### ISSUE THREAD

**Issue by checkaayush** [pyeve/eve#1304]
### Expected Behavior

Using `abort(402)` to handle [Payment Required](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402) error code should ideally return the following JSON response: 

```
{
  "_status": "ERR",
  "_error": {
    "code": 402,
    "message": "Payment Required"
  }
}
```

### Actual Behavior

```pytb
    
    ... abridged for brevity

    abort(402, description="Payment required")
  File "/usr/local/lib/python3.6/site-packages/werkzeug/exceptions.py", line 762, in abort
    return _aborter(status, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/werkzeug/exceptions.py", line 742, in __call__
    raise LookupError("no exception for %r" % code)
LookupError: no exception for 402
```

### Environment

* Python version: 3.6
* Eve version: v0.9.2

Happy to submit a PR if this is something we need.

**Comment by MacLotsen** [comment]
You can solve it in the link described. https://werkzeug.palletsprojects.com/en/0.15.x/exceptions/#custom-errors

**Comment by huandzh** [comment]
It may not work as expected with the method in the link https://werkzeug.palletsprojects.com/en/2.3.x/exceptions/#custom-errors

Here are the required steps to register a custom HTTP exception which returns **a standard response**:

1. Define the custom HTTP exception
3. Define a function to add it into `werkzeug.exception.default_exceptions`
4. Add exception code to `settings.py`
5. Call the function before creating the Eve instance in main

### codes


```python
# custom_exceptions.py
import werkzeug.exceptions as ex


class PaymentRequired(ex.HTTPException):
    code = 402
    description = "<p>Please purchase more.</p>"


def add_custom_exceptions():
    ex.default_exceptions[402] = PaymentRequired
```
```python
# settings.py

# add 402 to codes for which we want to return a standard response
STANDARD_ERRORS = [400, 401, 402, 403, 404, 405, 406, 409, 410, 412, 422, 428, 429]
```

```python
# main.py
from custom_exceptions import add_custom_exceptions

# add 402 PaymentRequired
add_custom_exceptions()

app = Eve(settings="settings.py")
# ...
```

#### Environment
* Python version: 3.11.6
* Eve version: v2.1.0
