### ISSUE TITLE
PATCH method is block by CORS policy

### ISSUE THREAD

**Issue by davidshen84** [pyeve/eve#1316]
### Expected Behavior

I should be able to PATCH an item with HTTP PATCH method.

Below is part of my *settings.py* file.
```python
DOMAIN = {'col1': {
    'schema': schema,
    'resource_methods': ['GET', 'POST'],
    'item_methods': ['GET', 'PUT', 'PATCH']
}}

ITEM_METHODS = ['GET', 'PUT', 'PATCH']
MONGO_HOST = '127.0.0.1'
MONGO_PORT = 27017

MONGO_USERNAME = 'testuser'
MONGO_PASSWORD = 'testuser'
MONGO_AUTH_SOURCE = 'test1'
MONGO_DBNAME = 'test1'

X_DOMAINS = ['http://localhost:4200', 'http://127.0.0.1:4200']
X_HEADERS = ['content-type']
```

### Actual Behavior

My request is blocked by CORS policy: Request header field if-match is not allowed by Access-Control-Allow-Headers in preflight response.

```pytb
None
```

I searched the web and found many people suggest using the flask-cors package to configure CORS with Eve. So I wonder what is the best practice to configure CORS policy in Eve.

### Environment

* Python version: 3.7.3
* Eve version: 0.9.2

**Comment by yuregir** [comment]
I am using PATCH successfully with this settings.
`X_DOMAINS = '*'
X_HEADERS = ['Content-Type', 'If-Match', 'Authorization', 'cache-control']`

**Comment by davidshen84** [comment]
@yuregir ,

Yes, your code solved my problem. Thanks!
