### ISSUE TITLE
Timestamp resolution

### ISSUE THREAD

**Issue by hughes** [pyeve/eve#1320]
I noticed that milliseconds are [explicitly removed](https://github.com/pyeve/eve/blob/e796a8c964e8db553b285375a5913ad87b1f5003/eve/methods/post.py#L160) from Date objects when setting the created/modified dates on documents before they're passed to MongoDB. The [underlying capabilities of mongo](https://docs.mongodb.com/manual/reference/method/Date/) will happily store milliseconds.

This is making it pretty difficult to tell which document is more recently modified in an environment where two documents being saved in the same second is likely. Is there any particular reason why milliseconds are discarded?

**Comment by nicolaiarocci** [comment]
That's because of RFC1123 http://www.csgnetwork.com/timerfc1123calc.html which is the format used by REST services (headers, If-Modified-Since, etc.)

**Comment by hughes** [comment]
I understand that's why the `DATE_FORMAT` used for adding the date to response content has a [default value](https://github.com/pyeve/eve/blob/master/eve/default_settings.py#L106) of RFC1123 formatting, but I don't understand why the underlying date object has milliseconds stripped. For the purpose of server-side operations like sorting, it makes it impossible to distinguish which document was more recently modified. 

For sorting by created date, it's still possible to sort by comparing the last 3 bytes of the objectid on documents with matching timestamps, but what can be used to distinguish the most recently modified of two such documents?

**Comment by nicolaiarocci** [comment]
Yes, good point. I suspect that removing that line would then require some more work to ensure everything works as expected on the output-side of things. Feel free to propose a PR, I will be happy to review it.
