### ISSUE TITLE
Eve example with gridfs

### ISSUE THREAD

**Issue by PaulSka** [pyeve/eve#1328]
Eve version : 0.9.2

I try to use simple example with Gridfs

I follow example https://docs.python-eve.org/en/stable/features.html#file-storage

So my settings is like

```
DOMAIN = {
    "accounts" : {
        "name": {"type": "string"},
        "pic": {"type": "media"},
    }
}
```
I try to push file with curl -F "file=@file.pdf" http://localhost:5000/accounts

But i give error {"_status": "ERR", "_issues": {"exception": "maximum recursion depth exceeded while calling a Python object"}, "_error": {"code": 422, "message": "Insertion failure: 1 document(s) contain(s) error(s)"}}

**Comment by stefaang** [comment]
There is no `file` field in the accounts resource.. you only have `name` and `pic`
Use this instead

    curl -F "name=someName" -F "pic=@file.pdf" http://localhost:5000/accounts
