### ISSUE TITLE
Update / Patch with same query like MongoDB

### ISSUE THREAD

**Issue by PaulSka** [pyeve/eve#1329]
Hi,

How can i update / patch existing element into database with same query like mongodb ?

For example, in mongodb i can use update_one(query, update) with update like {"$set" : {"a" : 2}, "$inc" : {"b" : 1}}

**Comment by PaulSka** [comment]
This raise error on pymongo

pymongo.errors.WriteError: The dollar ($) prefixed field '$set' in '$set' is not valid for storage.

**Comment by nicolaiarocci** [comment]
That is not supported. You can only PATCH at the document endpoint (`/people/123`)
