### ISSUE TITLE
Insert python datetime object with eve

### ISSUE THREAD

**Issue by PaulSka** [pyeve/eve#1340]
Hi,

I try to insert datetime.datetime python object into MongoDB with Eve (with python requests) but i have somes errors.

For example :

`data = {"msg" : "Hello", "date_msg": datetime.datetime(2019, 12, 16, 8, 0, 50, 99940)}`

If i post directly (requests.post(URL, json.dumps(data))) i have error with datetime serialization.

I use bson.json_util to add encoder, my data encoded with bson encoder looks like 

`data > {"msg": "Hello", "date_msg": {"$date": 1576483250099}} `
but i have new error on post (requests.post(URL, json.dumps(data, default=json_util.default)))

bson.errors.InvalidDocument: key '$date' must not start with '$'

How can achieve this ?

Thanks for help !

**Comment by nicolaiarocci** [comment]
Dates should be provided according to `DATE_FORMAT` configuration setting value (RFC1123 by default). Try something like this:

    data = {"msg" : "Hello", "date_msg": "Tue, 02 Apr 2013 10:29:13 GMT"}

See DATE_FORMAT in https://docs.python-eve.org/en/latest/config.html
