### ISSUE TITLE
Soft-delete restore not working

### ISSUE THREAD

**Issue by tanoabeleyra** [pyeve/eve#1346]
### Expected Behavior

After soft-deleting a resource a PATCH should restore it, according to [the documentation](https://docs.python-eve.org/en/stable/features.html#restoring-soft-deleted-items).

### Actual Behavior

When doing a PATCH request on a soft-deleted resource it returns **404**.
A PUT request returns **409**, *"Duplicate key error at index: 0"*.
The resource has `_deleted: true` at a DB level. I tried to manually change it to `false` and also remove it but nothing happens, it seems that there's something else going on behind the scenes (it doesn't simply look for a `_deleted` property, otherwise it would be restored).
Another thing that I noticed is that, even if I disable the soft-delete feature, the resources that were soft-deleted don't show up again, when [they should](https://docs.python-eve.org/en/stable/features.html#considerations).

This is the _relevant_ part of my domain:
```
    "places": {
        "schema": place,
        "allow_unknown": True,
    },
    "commerces": {
        "schema": commerce,
        "datasource": {
            "source": "places",
        },
        "soft_delete": True
    },
    "professionals": {
        "schema": professional,
        "datasource": {
            "source": "places"
        },
        "soft_delete": True
    }
```

This is an example of the request that I'm doing:
```
PATCH /api/commerces/5deebafd0816a917709ce1ba
{}
```

### Environment
* Python version: 3.8
* Eve version: 1.0

**Comment by tanoabeleyra** [comment]
It's a shame that such a nice framework doesn't have a bigger community, after one month I would expect some kind of feedback.

**Comment by gwainer** [comment]
Hi @tanoabeleyra, don't you have an index in this collection having `_deleted` as part of it? I had a similar problem with a unique index in the database when restoring a soft deleted document when another document with the index keys was already in place. It was created while the soft-deleted document was deleted.

**Comment by tanoabeleyra** [comment]
Hi @gwainer, I'm not really sure if I understood you, these are my indexes:

```python
"mongo_indexes": {
    "name": [("name", "text")],
    "fuzzy": [("fuzzy", 1)],
    "category": [("category", 1)],
    "type": [("type", 1)],
}
```

**Comment by gwainer** [comment]
OK, that does not seem to be the same problem I had, but still seems like an index is considering the `_deleted` key, by looking at the error message. Can you check in mongo console to see the indexes  like this:

`db.<COLLECTION_NAME>.getIndexes()`

There may be an index created outside eve causing trouble.
