### ISSUE TITLE
Need to support _id fields that are not ObjectId

### ISSUE THREAD

**Issue by roysmith** [pyeve/eve#136]
See https://groups.google.com/forum/#!topic/python-eve/sa3UcAfGk3M for discussion thread.

**Comment by arkanoid87** [comment]
I'm still on this problem
I can post items but I receive 404 on GET (e.g http://127.0.0.1:5000/my_resource/8f700138-650a-43b4-aa53-225d36c5e706)
I generate item["_id"] = uuid4() in insert_resource_xxx() hook
If I try to push the _id from the POST insertion I receive 422 "_validate_type_uuid() takes 2 positional arguments but 3 were given"
