### ISSUE TITLE
is $regex really unsafe?

### ISSUE THREAD

**Issue by arnauorriols** [pyeve/eve#1367]
Can we revisit the assumption that using `$regex` is unsafe and should be blacklisted by default? 

Our security department is blocking the usage of this feature because upstream (Eve) marks it as unsafe. However, some research and tests showed me that could no longer be the case. For example:

This halts execution in Python:
```
>>> re.match("^(([a-z])+.)+[A-Z]([a-z])+$", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa")
```

But MongoDB returns immediately:
```
> db.collection.insert({name: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"})
> db.collection.find({name: /^(([a-z])+.)+[A-Z]([a-z])+$/})
> db.version()
3.6.17
```

Some resources I've found:
- https://www.reddit.com/r/mongodb/comments/384j0q/redos_mongodb/
- https://jira.mongodb.org/browse/SERVER-17252

**Comment by nicolaiarocci** [comment]
@arnauorriols good point, I have no problem with removing `$regex`  from the blacklist. Please open a PR and I will be happy to merge it.
