### ISSUE TITLE
`last_created` and `last_updated` contain epoch when projection does not include them

### ISSUE THREAD

**Issue by arnauorriols** [pyeve/eve#1380]
As stated in [the docs of these functions](https://github.com/pyeve/eve/blob/ae73d09a5c31eaf5e80d68c15d2c832b807a18e5/eve/methods/common.py#L325-L346), the `LAST_UPDATED` and `LAST_CREATED` must always be present in the responses, and so these functions default to epoch. However, there's another case where the response might not contain these fields: when the user has not incuded them in the projection (or has excluded them). 

If these fields must always be present in the responses, then they should always be included in the projections.

To prepare a PR, I wonder where should we handle this: in `DataLayer._datasource_ex()` maybe?

**Comment by nicolaiarocci** [comment]
yes, looks like a good candidate.
