### ISSUE TITLE
Authentication error raises 500

### ISSUE THREAD

**Issue by luiscoms** [pyeve/eve#1400]
### Expected Behavior

When authentication fail Eve raise 500 error caused by output headers. When I comment lines [163-167](https://github.com/pyeve/eve/blob/v1.1.1/eve/render.py#L163-L166) it raises 403 error correctly.

```python
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 19:31:44] "GET /auth/verify HTTP/1.1" 403 -
```

### Actual Behavior

<img width="509" alt="Screen Shot 2020-07-02 at 19 31 20" src="https://user-images.githubusercontent.com/758273/86414641-eb7c5180-bc9a-11ea-81ed-e7c3429301ae.png">

```pytb
  File "/api/venv/lib/python3.7/site-packages/eve/endpoints.py", line 182, in error_endpoint
    return send_response(None, (response, None, None, error.code, headers))
  File "/api/venv/lib/python3.7/site-packages/eve/render.py", line 52, in decorated
    r = f(*args, **kwargs)
  File "/api/venv/lib/python3.7/site-packages/eve/render.py", line 92, in send_response
    return _prepare_response(resource, *response if response else [None])
  File "/api/venv/lib/python3.7/site-packages/eve/render.py", line 164, in _prepare_response
    for header, value in headers:
ValueError: not enough values to unpack (expected 2, got 1)
INFO:werkzeug:127.0.0.1 - - [02/Jul/2020 19:23:58] "GET /auth/verify HTTP/1.1" 500 -
```

### Environment

* Python version: 3.7
* Eve version: 1.1.1

> Update

I have found that when i call `abort` with response parameter a 500 erro rises

```python
from flask import abort, Response

abort(403, description='Please provide proper credentials', response=Response(None, 403))
```

**Comment by mapellidario** [comment]
I confirm the bug with python 3.8 and Eve `0.9` when using `TokenAuth` returning either `False` or `None`.

**However**, this bug seems to be resolved in Eve v1.1.3, the last release available at the time of writing.

Therefore, I would close this issue.
