### ISSUE TITLE
Multiple Patch requests on same document at time leads to race condition 

### ISSUE THREAD

**Issue by perumalla-giridhar** [pyeve/eve#1407]
---
### What happend?
I have multiple versions of an application running which are clients of mongodb, say app.v0 and app.v1
these apps communicate to mongodb through a python eve interface. 

I am running eve under uwsgi in a container. All the clients will send their requests to this container only. the write concern used in this python eve is `{'w': 1, j: true}`

when app.v0 and app.v1 process documents one after other. most of the cases they process same document at same time. The processing time is also almost same most of the cases. after processing they update their answer by adding a new field in the document. app.v0 add `{v0: 'itsanswer'}` to the document and app.v1 will add `{v1: 'itsanswer'}` field to the document. if both the update request take effect then my final state of document will have the `{answers: {v0: 'itsanswer', v1: 'itsanswer'}}`

when app.v0 and app.v1 send patch request at same time, only the last send patch request is been successful(race condition). In this case my document will have either `{answers: {v0: 'itsanswer'}}` or `{answers: {v1: 'itsanswer'}}`. In app.v0 and app.v1 , v0 is the production version. so if production answer is missed i get errors in later stage of pipeline.

### Expected Behavior
even when two patch requests are sent at same time on same document, both patch request should take effect. Means the final stage of document should be `{answers: {v0: 'itsanswer', v1: 'itsanswer'}}`

### Actual Behavior (Race condition)
there is a race between two patch requests which are sent at same time and only one is winning. the final state of document is either  `{answers: {v0: 'itsanswer'}}` or `{answers: {v1: 'itsanswer'}}`

with default write concern `{'w': 1}` this race condition used happen very frequently. after changing to `{'w': 1, j: true}` the occurrences of this issue is reduced but still exists. 

### Environment

* Python version: 3.6
* Eve version: 0.9.2

### Related Issue raised in Mongodb

This same issue is reported to mongodb. you can have a look at their response [here](https://developer.mongodb.com/community/forums/t/multiple-writes-on-same-document-within-journal-commit-interval-are-not-updated-in-the-document/8008/6?u=perumalla_giridhar)

### Additional Questions

is running eve under uwsgi is causing this race condition?
Is eve "thread-safe" ?

**Comment by nicolaiarocci** [comment]
Hello. Eve has not been designed with this scenario in mind (two instances updating the same db). What you could do however is have just one instance being hit by the two clients, each one updating his own field?
