### ISSUE TITLE
Refactor the test suite

### ISSUE THREAD

**Issue by ehiggs** [pyeve/eve#1425]
Testing Eve is difficult. In #1358 it was suggested that there might be a test infra refactor but there was no ticket to track it.

Some of the issues I've come across:

1. Testing against mongomock and pytest-mongomock is difficult because eve uses environment variables to configure instead of being able to easily pass in the mongo client to the app. (or if it is possible, it's not obvious to me).
2. No Dockerfile or docker-compose configuration to easily spin up a test infra.
3. No coverage.

**Comment by nicolaiarocci** [comment]
hi @ehiggs yes, by all means, if you have the time to work on this, I'm all for it.
