### ISSUE TITLE
Live demo broken?

### ISSUE THREAD

**Issue by opensorceror** [pyeve/eve#1431]
The [live demo](https://eve-demo.herokuapp.com/people) doesn’t load for me. Heroku shows a screen with the following message:

> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail

**Comment by nicolaiarocci** [comment]
Yeah, Heroku has dropped support for our free demo instance. If you look at the 'latest' documentation, references to the live demo have been removed (https://docs.python-eve.org/en/latest/).

**Comment by nicolaiarocci** [comment]
which reminds me, we should release a new stable version soon. I am only waiting for #1429 to be finalized

**Comment by D-stefaang** [comment]
Yeah sorry about that.. I had given up on getting the tests locally and thought it would be trivial via Jenkins, but it has taken me way more cycles than expected. It's high on my agenda this week.
