### ISSUE TITLE
Is Eve still maintained?

### ISSUE THREAD

**Issue by itsjef** [pyeve/eve#1458]

**Comment by nicolaiarocci** [comment]
Hello, thanks for asking. Here's my answer, also posted on [my website](https://nicolaiarocci.com/is-eve-still-maintained/):

Hello, yes, Eve is in ‘maintenance mode’, as I call it. I don’t actively develop new features anymore. Still, I am more than willing to code-review and merge relevant pull requests, especially so if they are bug fixes or improvements over existing features.

Long story short, after many years of development, the funding campaign[^1] that would have allowed me to keep working on the project failed miserably. People are using the framework worldwide, probably making a profit out of it, but they are not interested in investing in it[^2]. The good news is that the framework is, I think, stable and mature enough to meet most needs.

With Cerberus, I was lucky enough to find a worthy, skilled maintainer in the person of @funkyfuture, who’s keeping the project going. I am hoping the same happens with Eve. So, if anyone familiar with the code-base is willing to help, this is your moment to come forward. Maybe start with triaging open tickets, maybe pull-request for some low-hanging fruits, and then challenge yourself with more demanding tasks, like updating Eve to the latest version of Cerberus.

I had so many things planned for Eve. Hopefully someone will join the ranks, maybe take the helm, and help bring it to the next level.

[^1]: I must admit, this failure hit me hard.
 [^2]: For some rationale behind the campaign, see [this post](http://nicolaiarocci.com/eve-and-cerberus-funding-campaign/) from 2017.
