### ISSUE TITLE
Render fails because recent version of Werkzeug has removed escape() method from utils

### ISSUE THREAD

**Issue by heharkon** [pyeve/eve#1474]
The render fails with recent versions (2.1.x) of Werkzeug as they have removed the escape method from utils module.

Here's their change commit:

https://github.com/pallets/werkzeug/commit/22d1e9ac13829b83347107a9b4d77072a8e1af6a

Usage of escape() in Eve:

render.py, method xml_add_links():
    chunk % (rel, utils.escape(d["href"]), utils.escape(d["title"]))

### Environment

* Python version: 3.10
* Eve version: 1.1.5

**Comment by nicolaiarocci** [comment]
appears to be fixed by #1473

**Comment by heharkon** [comment]
Ah, should have tried with the dev version... Thanks! And sorry for the unnecessary bug report. 😊

**Comment by nicolaiarocci** [comment]
it's ok, tge pull request is not merged yet anyway.

**Comment by nicolaiarocci** [comment]
this should be now fixed

**Comment by gubasso** [comment]
I'm trying to pull off a project with Eve, but I the last version installed still has this issue (Eve = "^1.1.5"): `AttributeError: module 'werkzeug.utils' has no attribute 'escape'`

Which version do I install to get Eve working correctly today?

**Comment by nicolaiarocci** [comment]
Hi, you should wait for v2 release, or use the current `master` branch.
