### ISSUE TITLE
Add support to release Linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [pyeve/eve#1480]
Problem
---------
On aarch64, ‘pip install Eve’ builds the wheels from the source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from PyPI. 

Resolution
-----------
On aarch64, ‘pip install Eve’ should download the wheels from PyPI.

@nicolaiarocci and Team Please let me know your interest in releasing aarch64 wheels. I can help in this.

**Comment by nicolaiarocci** [comment]
hi, please feel free to submit a PR. I'll be happy to review it.

**Comment by nicolaiarocci** [comment]
v2.0 now has wheels included
