### ISSUE TITLE
Malformed Last Updated field

### ISSUE THREAD

**Issue by luiscoms** [pyeve/eve#1490]
### Expected Behavior

I set `DATE_FORMAT` config with following value

```python
DATE_FORMAT = '%Y-%m-%d %H:%M:%S%z'
```
When I get resource, the `_updated` field does not show timezone

### Actual Behavior

Result of get resource:

![Screenshot from 2022-10-19 17-25-11](https://user-images.githubusercontent.com/758273/196797549-c217b636-17bb-49cd-80f9-a2da5f99f9e5.png)

Fields on MongoDB
![Screenshot from 2022-10-19 17-19-50](https://user-images.githubusercontent.com/758273/196797570-848209bb-ccd6-4051-a5f5-73ced8f39439.png)

### Environment

* Python version: 3.9.9

```bash
pip freeze -r requirements.txt
config-client==1.1.0
Eve==1.1.5
Eve-Elastic==7.2.1
eve-healthcheck==0.3.1
gunicorn==20.1.0
MarkupSafe==1.1.1
PyQueueManager==1.12.1
PyYAML==6.0
```

**Comment by luiscoms** [comment]
I've teste with `Eve==2.0.2` too, same problem

**Comment by nicolaiarocci** [comment]
This is intended behavior, see [this](https://github.com/pyeve/eve/blob/master/eve/methods/common.py#L332) for the reasoning around it.

**Comment by luiscoms** [comment]
Ok, but Eve set UTC time [here](https://github.com/pyeve/eve/blob/master/eve/methods/common.py#L1514), does not make sense to remove tzinfo

**Comment by nicolaiarocci** [comment]
Hmm, that's the oplog push code, and in a conditional branch only executed when the last update info not available. Furthermore, it's set at UTC precisely because all last_updates must be timezone-less (see my link above.)

**Comment by luiscoms** [comment]
It was only an example code, [here](https://github.com/pyeve/eve/blob/4fe93450b39a2dfeaf4f3343b5669f872d133c1c/eve/methods/patch.py#L201) another example

**Comment by luiscoms** [comment]
A possible fix is 

```diff
- updates[config.LAST_UPDATED] = datetime.utcnow().replace(microsecond=0)
+ updates[config.LAST_UPDATED] = datetime.utcnow().replace(microsecond=0, tzinfo=timezone.utc)
```

**Comment by nicolaiarocci** [comment]
Feel free to submit a PR, I'll be happy to review it.
