### ISSUE TITLE
Tests folder in eve distribution

### ISSUE THREAD

**Issue by guillaumeLepape** [pyeve/eve#1506]
---

### Expected Behavior

We usually avoid to include tests in Python distribution.

### Actual Behavior

Eve distribution contains tests.

### Environment

* Python version: test with python 3.8, same behavior with other python versions
* Eve version: last version

### Steps to reproduce on linux machine

```sh
$ python -m venv env
$ . env/bin/activate
$ pip install eve
$ ls env/lib/python3.8/site-packages/eve
__init__.py     auth.py                     defaults.py     exceptions.py  io                methods   tests      validation.py
__pycache__  default_settings.py  endpoints.py  flaskapp.py      logging.py  render.py  utils.py  versioning.py
```

We should not see the `tests` folder here.

### Possible solution

Moving the tests folder from `eve` to the root folder of the project. Modify the test path in configuration files to make sure there are still run.

**Comment by guillaumeLepape** [comment]
I can procede with these changes if ok to you.

**Comment by nicolaiarocci** [comment]
sure, go ahead. Thanks.

**Comment by guillaumeLepape** [comment]
https://github.com/pyeve/eve/pull/1507
