### ISSUE TITLE
HTTP response code on failure

### ISSUE THREAD

**Issue by jaagr** [pyeve/eve#201]
I just "pipped" Eve since it looks promising. However when trying it out I immediately noticed something with the HTTP response status codes.

For example, when I try to post a resource and the validation fails I get a `HTTP/1.0 200 OK` response. The response got delivered, ok I get that, but the server didn't fulfill the request so it should be a 403.

Returning information about errors with a 200 OK is not really RESTful.

**Comment by anton-kaidalov** [comment]
Oh why :) I need exactly the "partially-accepted" behavior, and it turns out you've had it, but then removed it.

Do I understand correctly there's no way anymore to configure Eve to accept bulk inserts partially?
