### ISSUE TITLE
having aggregation option for GET requests

### ISSUE THREAD

**Issue by tony7126** [pyeve/eve#208]
certain analytics I'd like to make available on my analytics endpoints depend on the MongoDB aggregation framework.  It would be great if there were a way to specify the fields you'd like to group on, how you want to group (sum, avg, etc...).

**Comment by nicolaiarocci** [comment]
FYI aggregation framework support has been merged to eve-dev: http://python-eve.org/features#mongodb-aggregation-framework

**Comment by nrchandan** [comment]
@nicolaiarocci I think you can close this one.

**Comment by nicolaiarocci** [comment]
Right 😃
