### ISSUE TITLE
use flask blueprint for eve app

### ISSUE THREAD

**Issue by ilovenwd** [pyeve/eve#227]
It will be more convenient for composing eve app with existing flask app if eve app is a blueprint. Current eve flask app can be just a thin wrapper of the eve blueprint.

for example:

``` python
class EveBlueprint(Blueprint):
   pass

class Eve(Flask):
   register_blueprint(EveBlueprint)
```

**Comment by harobed** [comment]
@amagdas have you finished your PR ?

**Comment by AndrewPashkin** [comment]
@sebasmagri
@nicolaiarocci 
>Roughly looked at this but it doesn't seem to be a straightforward task. Mainly due to the way Eve's configuration is loaded and routes are setup from DOMAIN. To use a blueprint we'd need to change this and probably make the resources initialization more lazy.

Another problem is with events. Currently Eve class inherits from `Events`, which would be impossible in case of introduction of blueprint. So backwards-incompatible change of API would be required.

**Comment by AndrewPashkin** [comment]
Maybe it is better to talk not about blueprint, but about extension?

**Comment by julianhille** [comment]
I could do a pr or build an extension cause i already Have something with
blueprints what i usw currently

Andrew Pashkin <notifications@github.com> schrieb am Sa., 9. Apr. 2016
11:37:
