### ISSUE TITLE
RFE: More comprehensive ACL implementation

### ISSUE THREAD

**Issue by mickep76** [pyeve/eve#228]
Currently I use my own ACL implementation on top of Eve since it needs to be very flexible and granular. However it would be nice to have this func. build in.

First I have 2 layers of ACL's per Application and per Item. So for this I use the following endpoints:

**Simplified Example:**

<pre>
role: {
    'additional_lookup': {
        'url': 'string',
        'field': 'role',
    },

    'schema': {
        'role': {
            'type': 'string',
            'required': True,
            'unique': True,
        },
        'perm': {
            'type': 'string',
            'allowed': [ 'GET', 'PATCH', 'PUT', 'DELETE' ],
            'required': True,
        }
}

acl = {
    'additional_lookup': {
        'url': 'string',
        'field': 'acl',
    },

    'schema': {
        'type': 'list',
        'validate_acl': True,
        'schema': {
            'type': 'dict',
            'schema': {
                'user': {
                    'type': 'objectid',
                    'data_relation': {
                        'resource': 'users',
                        'field': '_id',
                    },
                    'required': True,
                },
                'role': {
                    'type': 'objectid',
                    'data_relation': {
                        'resource': 'roles',
                        'field': '_id',
                    },
                    'required': True,
                }
            }
        }
    }
}

user = {
    'additional_lookup': {
        'url': 'string',
        'field': 'username',
    },

    'schema': {
        'username': {
            'type': 'string',
            'required': True,
            'unique': True,
        },
        'name': {
            'type': 'string',
            'required': True,
        },
        'email': {
            'type': 'string',
            'required': True,
        },
        'acl': {
            'type': 'objectid',
            'data_relation': {
                'resource': 'acl',
                'field': '_id',
            },
            'required': True,
        }
}

app = {
    'additional_lookup': {
        'url': 'string',
        'field': 'name',
    },

    'schema': {
        'name': {
            'type': 'string',
            'required': True,
            'unique': True,
        },
        'version': {
            'type': 'string',
            'required': True,
            'unique': True,
        },
        'acl': {
            'type': 'objectid',
            'data_relation': {
                'resource': 'acl',
                'field': '_id',
            },
            'required': True,
        }
    }
}    

myitem = {
    'additional_lookup': {
        'url': 'string',
        'field': 'myitem',
    },

    'schema': {
        'myitem': {
            'type': 'string',
            'required': True,
            'unique': True,
        },
        'acl': {
            'type': 'objectid',
            'data_relation': {
                'resource': 'acl',
                'field': '_id',
            },
            'required': True,
        }
    }
}
</pre>

This means using the same model you can implement a very granular and flexible security layer, without having to create multiple end points. The drawback is that it req. more storage.

**Comment by jameslittle** [comment]
I'd also like to see content-based auth; you may have AUTH_FIELD enabled for GETs because generally you don't want _everything_ to be public, but the owner/creator of a particular document may want to make it public. I've hacked io/base.py (something like below) to do this, but feel there should probably be a more general way of OR'ing queries wrt auth to allow for more complex scenarios (e.g. "I want my list of _friends_ to be able to to see this")

                    else:
                        query = self.app.data.combine_queries(
                            query, { '$or': [{auth_field: request_auth_value}, {'visibility':'public'}] }
                        )
                else:
                    query = { '$or': [{auth_field: request_auth_value}, {'visibility':'public'}] }
