### ISSUE TITLE
Allow updates using positional operator

### ISSUE THREAD

**Issue by tony7126** [pyeve/eve#229]
I want to be able to somehow specify which object in the array to update based on an arbitrary field value.  So in mongo for

```
{
   _id: 12345
   list_of_objects: [{ attr1: "val1", attr2: val2}, {attr1: "val3", attr2": val4}]
} 
```

If I wanted to update "attr2" where "attr1" had a value of "val1" I would do something like:

```
db.collection.update({"_id": 12345, "list_of_objects.$.attr1": "val1"},
{"$set": {"list_of_objects.$.attr2": new_val}})
```

Maybe I'm missing something but I haven't been able to find a clean way to update a specific object in an array in one API call.

**Comment by gladuo** [comment]
Is it ok know?

**Comment by gladuo** [comment]
Is it ok now?

**Comment by sapamja** [comment]
Apart from updating the document inside the list, is it possible to append docs in the list. For example like if I have time series data to update in a list.
