### ISSUE TITLE
Trouble serializing list of dicts

### ISSUE THREAD

**Issue by joshvillbrandt** [pyeve/eve#265]
I have a schema that contains the rollowing relavent pieces:

``` python
myresource = {
    'schema': {

        'roles': {
            'type': 'list',
            'required': True,
            'schema': {
                'type': 'dict',
                'schema': {

                    ID_FIELD: {
                        'type': 'objectid',
                        'required': True,
                    },
                    'name': {
                        'type': 'string',
                        'minlength': 1,
                        'maxlength': 255,
                        'required': True,
                    }

                }
            }
        }

    }
}
```

When I do a PUT request against an individual document with two `roles`, the first id will be serialized just fine, but the second id gets a message like this: `roles: {"1":{"_id":"value '530bf8ca85f27a2007a76a18' cannot be converted to a ObjectId"}}`.

I did some digging into `serialize()` function in common.py. I can't quite understand [this chunk of code](https://github.com/nicolaiarocci/eve/blob/develop/eve/methods/common.py#L302-L316):

``` python
if 'dict' in (field_type, field_schema.get('type', '')):
    # either a dict or a list of dicts
    embedded = [document[field]] if field_type == 'dict' \
        else document[field]
    for subdocument in embedded:
        # serialize subdocument
        if 'schema' in field_schema:
            serialize(subdocument,
                      schema=field_schema['schema'])
        # serialize fields of subdocuments
        for subfield, v in subdocument.items():
            subfield_type = \
                field_schema[subfield].get('type')
            if subfield_type in app.data.serializers:
                document[field][subfield] = \
                    app.data.serializers[subfield_type](v)
```

It seems like all of the subdocuments fields are serialized once under `# serialize subdocument` and then again in `# serialize fields of subdocuments`. If I comment out the lines under `# serialize fields of subdocuments`, everything works as expected. Are these pieces of code doing the same thing?

I imagine you're covering for schema scenarios that aren't presented in my resource definition, but this chunk of code is a bit convoluted, so I don't understand what's going on. Any ideas?

**Comment by Eibriel** [comment]
Error validating a list of ObjectIDs, on Python 3.4 and EVE 0.5.4 via PIP on virtualenv (linux)

### Scheme
```
products': {
        'type': 'list',
        'schema': {
            'type': 'objectid',
            'data_relation': {
                'resource': 'products',
                'field': '_id'
            }
        }
    }
```

### Error
```
{"_status": "ERR", "_issues": {"products": {"0": "value '5595f431d052ac00092f541d' cannot be converted to a ObjectId"}}}
```
