### ISSUE TITLE
404 and 401 not CORS compatible

### ISSUE THREAD

**Issue by joshvillbrandt** [pyeve/eve#269]
Hey @nicolaiarocci, can we make 404 and 401 errors (actually, all responses...) CORS compatible? I see that you jump directly to flask's Response function when handling 401's in `auth.py` which skips all of your CORS logic in `render.py`. The effect is that I get bunch of errors like:

```
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

even when I have Eve configured properly.

**Comment by kumy** [comment]
This caused us lots of troubles with newer Firefox (> 39?).

When Http `401` was returned, FF said `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://xxxxxxxxxx. (Reason: CORS request failed).`.

Update the function as this (as an override) solved the problem for us.
From `class BasicAuth`:
```
    def authenticate(self):
        """ Returns a standard a 401 response that enables basic auth.
        Override if you want to change the response and/or the realm.
        """
        resp = Response(None, 401, {'WWW-Authenticate': 'Basic realm="%s"' %
                                    __package__})
        abort(401, description='Please provide proper credentials',
              response=resp)

```

To:
```
def authenticate(self):                                           
    """ Returns a standard a 401 response that enables basic auth.
    Override if you want to change the response and/or the realm. 
    """                                                           
    return Response(None, 401, {'WWW-Authenticate': 'Basic realm="%s"' %
                                    __package__})

```

**Comment by nicolaiarocci** [comment]
thanks @kumy!
