### ISSUE TITLE
How to use regex in Get request

### ISSUE THREAD

**Issue by HansenLiu** [pyeve/eve#322]
May I use regex in get request like where={"name":{"$regex":"abc*"}} ?

**Comment by chromano** [comment]
> The `$regex` operator is supported, but it is blacklisted by default (`default_settings.py` contains `MONGO_QUERY_BLACKLIST = ['$where', '$regex']`).
> 
> 1. add `MONGO_QUERY_BLACKLIST = ['$where']` to your settings.py
> 2. query your API like this: `?where={"name": {"$regex": ".*foo.*"}}`
> 
> Be careful however. If you don't control the client, enabling regexes could potentially increase your API vulnerability.

I guess Nicola refers to [ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS).
