### ISSUE TITLE
Eve class parameter 'template_folder' only works with full path

### ISSUE THREAD

**Issue by diogo** [pyeve/eve#325]
The function render_template only works with the full path to the template_folder parameter.
The defaults value of render_template don't works, and relative paths don't works too.

**Comment by aguegu** [comment]
As a quick check on flask source code. 

https://github.com/mitsuhiko/flask/blob/master/flask/helpers.py#L832

the difference is on its.root_path

With eve, the root_path would be the eve location, like 'venv/lib/python2.7/site-packages/eve'. That is why relative paths would never work. 

I think eve can set it back to normal.
