### ISSUE TITLE
Date-based Filtering

### ISSUE THREAD

**Issue by mikej165** [pyeve/eve#349]
I'm attempting to query and filter to just documents created between two dates, as shown below. This query will return documents in the Mongo shell but not from Eve. The date format appears to be correct.  I couldn't find any date-based filtering examples in the docs, so I turn here hoping that someone else has run into this.

```
/api/newsletters?where={"$text":{"$search":"snowden"},"created_at": {"$gte":"Mon, May 26 2014 00:00:00 GMT", "$lte":"Thu, May 29 2014 00:00:00 GMT"}}&sort=[("created_at", -1)]&page=1
```

**Comment by janreyho** [comment]
how to use curl to filter document by Date? for example:
`curl -i http://localhost:5000/api/newsletters?where={"created_at": {"$gte":"Mon, May 26 2014 00:00:00 GMT", "$lte":"Thu, May 29 2014 00:00:00 GMT"}}`
