### ISSUE TITLE
OAuth or OAuth2 Support

### ISSUE THREAD

**Issue by EmergentBehavior** [pyeve/eve#447]
Will this ever be included into the framework? If not, are there any guidelines for integrating something like Flask-OAuthlib?

**Comment by nicolaiarocci** [comment]
@EmergentBehavior great job with that example. How do you get tokens pushed to redis though? Can't see anything like that being done in the provider code, while the `BearerAuth` snippet above is using redis to authenticate the token. I suppose it's done by Flask-Oauthlib itself, do I need to set some configuration options maybe? Thanks!

**Comment by EmergentBehavior** [comment]
Yeah most of that happens with Flask-OAuthlib. I have some code where it uses MongoDB to hold authentication data and added some lines where it adds/removes active/inactive tokens to the Redis cache.

**Comment by EmergentBehavior** [comment]
Check here:

https://github.com/brunsgaard/yoloAPI/blob/feat/2_mongodb-redis-support/models.py#L204-L208

and

https://github.com/brunsgaard/yoloAPI/blob/feat/2_mongodb-redis-support/models.py#L165-L170

**Comment by nicolaiarocci** [comment]
Ah I see now I think the last commit was missing from the repo. You're also using mongoalchemy now, cool. I did [a clone of your work last week](https://github.com/nicolaiarocci/flask-oauth2), and update it to work with mongo (not using orm though). I'll look to your updated code in the coming days... maybe I can just use it instead :)

**Comment by EmergentBehavior** [comment]
Cool! This is why I like open-source stuff. If you could throw my handle and @brunsgaard in the acknowledgements I'd appreciate it (then I can show off to the other kids :).

I don't know that I'll be able to work more on it soon as I've been focused on other projects (a platform for work and Storj) so yours may end up developing faster.

**Comment by nicolaiarocci** [comment]
Done! Awesome!

**Comment by antonrifco** [comment]
cool
