### ISSUE TITLE
Should URL_PROTOCOL be removed from the docs?

### ISSUE THREAD

**Issue by sevein** [pyeve/eve#473]
It seems that URL_PROTOCOL is not used anymore after 69b8141c0c5f10e8d4221e56228a80cb0bc92bd6 (refs #401, #398).

I'm happy to do this myself but I figured I'd check with you before.

**Comment by girogiro** [comment]
One more inconsistency - when `http://www.example.com/api/countries` is requested using the configuration above, the parent link contains '/'. However, this semantically means `http://www.example.com`. To get the correct one `http://www.example.com/api`, the link relative to API entry point would have been `.` according to [RFC1808] (http://ftp.isi.edu/in-notes/rfc1808.txt) specifying relative links (see Section 5).

Anyway, I am not sure if there is any benefit of the `parent` link for the user. All the information he already knows from the URL he requested.
