### ISSUE TITLE
Dynamic database via a prefix?

### ISSUE THREAD

**Issue by nikolay** [pyeve/eve#507]
Is it possible to create a workaround for the situation where I want the top resource to be the MongoDB database name? Anyway, it would be a nice feature to allow access to multiple databases out of the box.

**Comment by aguirrel** [comment]
Hi @nicolaiarocci, I'm interested in this new feature too! do you have any update about this?

**Comment by nicolaiarocci** [comment]
Still planned for release! I am personally interested in this feature so I guess that you can count on it. It's just being postponed to 0.6 as 0.5 is so full of features already (and is probably going to be released this month anyway).

**Comment by aguirrel** [comment]
Great!  In the meantime is there some hack that may it work? Just like using on_fetched_item and on_insert_item to change app.data.driver.db "on the fly"?

**Comment by nicolaiarocci** [comment]
Hmm you can experiment with that. The multi-mongo branch is online if you want to see what's been cooking so far: https://github.com/nicolaiarocci/eve/compare/multi-mongo-db

**Comment by aguirrel** [comment]
Thanks a lot! I will check it!
