### ISSUE TITLE
About how Eve manage readonly fields and how improve them in PATCH operations

### ISSUE THREAD

**Issue by pfreixes** [pyeve/eve#519]
Current implementation of patch operation gets out from the original document those `readonly` fields that they don't have default because of Eve uses the `dict.update` method directly.

Eve says nothing about that the default values are a must for a read only fields, therefore those values got from `readonly` fields should be keep it at each update.

Have a look to the next snippet, it tries to figure out which `readonly` fields are in the original document and keep them.

```
>>> original = {"foo" : {"code": 100}}
>>> updates = {"hello": "world"}
>>> schema = {"foo": {'type': 'dict', 'schema': { 'code': { 'type': 'integer', 'readonly': True}}}, "hello": {"type": "string"}}
>>> update_keeping_readonly_fields(original, updates, schema) 
>>> original
{'hello': 'world', 'foo': {'code': 100}}
```

The idea behind `update_keeping_readonly_fields` is just make a update as a original `dict.update`method but keeping the **readonly** fields.

Continuing with this subject, **readonly** fields with no default values, the scenario explained below should be consider to change how Eve is calculatiing **Etag** today. 

Readonly fields are used along with the other fields to get the etag values but these,  at last read only,  can't be updated for the user. The idea behind **Etag** is give to the user a way to check that it holds the last version of the document , otherwise apply some kind of mechanism at user side to merge last changes . Then the use of **readonly** fields without default values as a fields to get the Etag value doesn't make sense.

These proposed changes can be used to handle **readonly** fields without default values aside of the Eve without breaking the idiosyncrasy of Eve. It means that other processes can directly update these fields using other tools and other requirements.

I'm working with a branch to implement these modifications but first of all I would like to know what you think of this.

**Comment by pfreixes** [comment]
HI @nicolaiarocci have you considered the `etag` attribute? I can code this new feature and make a pull request.

**Comment by nicolaiarocci** [comment]
@pfreixes sorry I did not get back to you on your last question. I think it can be useful so feel free to submit a PR for `etag` field-level attribute.

**Comment by pfreixes** [comment]
@nicolaiarocci etag feature was inserted by the commit d7e9bd02 therefore forget it
