### ISSUE TITLE
allow projections on embedded resources

### ISSUE THREAD

**Issue by doshprompt** [pyeve/eve#578]
Hi,

I have an embedded list of child objects referenced by ids in the parent object like so

```
parent: {
  "children: [ "child1", "child2"]
}
```

The schema for my child object is like so

```
child: {
  "a": "x",
  "b": "y",
  "c": "z"
}
```

I would like a way to retrieve a list of parent records, along with the embedded children, but where each child contains only fields `a` and `c`

Something like this

`GET /parents?max_results=10&embedded={"children":1}&projection={"children.a":1,"children.c":1}`

Please let me know if there is planned support for this and/or if it is at all possible as my children objects contain a lot of fields and I only require a very small subset of them when I query for the parents, so it will help us greatly speed up the response time and improve performance dramatically on the client-side.

**Comment by rs** [comment]
+1

**Comment by pfreixes** [comment]
looks a good idea

On Thu, Mar 19, 2015 at 11:38 PM, Olivier Poitrey <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicolaiarocci/eve/issues/578#issuecomment-83788351>.
>



-- 
--pau

**Comment by nicolaiarocci** [comment]
MongoDB projections apply to parent document and/or its embedded documents. In your use case we are dealing with references, so projections would not work without a lot of black magic or relying to the aggregation framework. Ideally this implementation sit one layer above the DataLayer, so other engines can enjoy it, so I am experimenting with a slightly different approach. 

I assembled a prototype which relies on adding support for dot notation for `embedded` argument. So:

    GET /parents?embedded={"children.a":1}

Would return something like:

        {
           "parent_field1": "value",
           "children": [{"a": "x"}, {"a": "c"}]}
        }

You can still do `embedded={"children":1}` to get the whole thing back of course, and projections keep working as usual so you can limit parent fieldset as well. There's still some rough corners though, so before I go down this route I wanted to ask if you guys feel like this is an acceptable approach.

**Comment by doshprompt** [comment]
@nicolaiarocci this looks good, it's probably also more concise in terms of the query string params. I think it's acceptable to me, not sure what the others think but @rs is likely to agree with your approach as well.

**Comment by rs** [comment]
Why not merging both embedding and projection concepts into a single API? The Facebook way is quite nice IMHA, with the `fields` parameter you can select what fields and perform "sub requests" which is basically what you call embedding. The notation is: `fields=somefield,someobjectfield{subfield1,subfield2}`.

More info here: https://developers.facebook.com/docs/graph-api/using-graph-api/v2.2#fieldexpansion

**Comment by nicolaiarocci** [comment]
As it stands now, embedding and projections are two very different things. Projections are processed directly by the MongoDB driver, as Mongo natively supports them; Eve embeds on the other hand are more powerful than Mongo's, as they work across different collection too and, more importantly, they are dealt with at the business layer.

It would probably take a lot of work (and backwards compatibiity breakage) to refactor the current implementation to match Facebooks', which I concur, is nice.

**Comment by rs** [comment]
The underlaying implementation shouldn't prevent us from having a clean and easy to use API. The logic interpreting the `fields` parameter could happen very early in the request processing, and translate to current notations internally so it can still use Mongo's native handling.



With an option, we could also still allow the current notation for backward compat.

**Comment by nam4dev** [comment]
+1

**Comment by mohierf** [comment]
+1

**Comment by janreyho** [comment]
+1

**Comment by satyanani40** [comment]
Hi Nicola Iarocci did you  implemented this feature

My use case: 

'related_stores': {
            'type': 'list',
            'schema': {
                'type': 'objectid',
                'data_relation': {
                    'resource': 'stores',
                    'embeddable': True,
                    'field': '_id'
                }
            }
        }

embedded document query: embedded={"related_stores.name:1}
it will return stores names in related_stores field.
