### ISSUE TITLE
How to get user authenticated?

### ISSUE THREAD

**Issue by horacioibrahim** [pyeve/eve#679]
Hi! 

I need to get the current user authenticated as `http://api.example.com/api/me`. I have used two resources `users` and `me` to access `user` collection with `auth_field`. Follows my "solution":

``` python

DOMAIN = {
    'users': {
        'url': 'users',
        'datasource': {
            'source': 'user',
                'projection': {'password': 0}
        } ...
   }, # end Users definition
    'me': {
        'url': 'me',
        'datasource': {
            'source': 'user', # same source of the users
            'projection': {'password': 0}
        },
         'auth_field': 'owner',
     ...
   }
}
```

With solution I can to return only documents from users resources (or user collection in MongoDB) as a query done `on *resource*` instead `on *item*`. The Eve makes `GET`: if `on item` the outcome would be the `item` as GET on /users/[user_id] or if `on resources` the '_items' are part of the JSON output.

in truth: I want to do `GET` on `resource` and return one `item`.

To solve it I have created a hook that changes the `response` called `before_returning_items_from_me`.

``` python

def before_returning_items_from_me(response):
    output = response['_items'][0]

    # cleaner and keeping id
    for k, v in response.items():
        del(response[k])

    for k, v in output.items():
        response[k] = v

...
# __init__.py
app = Eve(...)
app.on_fetched_resource_me += before_returning_items_from_me
```

This function makes `response` to return the item[0] and particularly solved my problem. **my question** ....

There is another solution to return the authenticated user (or current user)?

**Comment by andy37380** [comment]
You need set user's field 'owner' value = user's field '_id' value when you create user.
Then ```on resources``` /users ```GET``` will return your own user
```
user = {
	'auth_field' : 'owner',
         ignore.....
}
```

**Comment by horacioibrahim** [comment]
Yes @andy37380. But this will return a list, something as {"_items": [`object`]}. However, I only wants the item[0]. So the `object`.

* where `object` is my desired result.

It's a question of semantic. Something as **If I gets /me only interest my account data.** (and a list is unnecessary). 

Thanks for your hints.
