### ISSUE TITLE
Support Mongo geo-queries legacy syntax

### ISSUE THREAD

**Issue by arnauorriols** [pyeve/eve#695]
I'm still not sure if there is a valid use case for this request, but here it is anyway. Currently, Eve supports All the Geospatial queries of Mongo using the $geometry operator:

``` Javascript
?where={
    "location": {
        "$near": {
            "$geometry": {
                "type":"Point", 
                "coordinates": [10.0, 20.0]
            }, 
            "$maxDistance": 1000
        }
    }
}
```

For the `$near` and `$nearSphere` operators, there is a legacy syntax that can be used:

``` Javascript
?where={
    "location": {
        "$near": [10.0, 20.0],
        "$maxDistance": 1000
    }
}
```

Which is not supported by Eve. I'm not sure about the whole scope, but at a first sight seems that the only bit missing is adding all the options used by `$near` and `nearSphere` (like `$maxDistance`) to the set of supported operators.

I'll work on a PR myself if OK.

**Comment by nicolaiarocci** [comment]
Yes I think this would be a nice addition to have. Looking forward to your upcoming contribution :+1:
