### ISSUE TITLE
Request: Method for (or docs explaining how to) get debug dump of json/input on rejected requests in eve

### ISSUE THREAD

**Issue by milutz** [pyeve/eve#710]
I've had a heck of a time working out why I've had requests rejected with 412 and 422 returns (I now know what those codes mean, but the rejects happened before all common eve app code runs, so I was extra flustered that I couldn't figure out how to display the offending data that was being sent to eve).

After lots of digging (and really being tipped off by SO: http://stackoverflow.com/questions/27142276/python-eve-412-precondition-failed-on-patch  I wrote the following to display all data on the requests I was having trouble with so I could figure out what was being rejected:

```
def pre_get_callback(resource, request, lookup):
    print 'DEBUG-GET: "{0}" endpoint - args: {2}, body: {1}, data: {3}'.format(resource, str(request.form), str(request.args), str(request.data))

def pre_post_callback(resource, request):
    print 'DEBUG-POST: "{0}" endpoint - args: {2}, body: {1}, data: {3}'.format(resource, str(request.form), str(request.args), str(request.data))

def pre_patch_callback(resource, request, lookup):
    print 'DEBUG-PATCH: "{0}" endpoint - args: {2}, body: {1}, data: {3}'.format(resource, str(request.form), str(request.args), str(request.data))

if __name__ == '__main__':
    app.on_pre_GET += pre_get_callback
    app.on_pre_POST += pre_post_callback
    app.on_pre_PATCH += pre_patch_callback
    app.run(host='0.0.0.0', port=5555, debug=True)
```

I think it would help the project if either a more streamline methodology was introduced to dump the data thats causing rejects in Eve, or if explicit example code was added to the docs to enable boneheads like me to more easily debug Eve projects

All the best,
-Mike

**Comment by nicolaiarocci** [comment]
I agree that a lot of people are getting stuck there. Documentation should be updated, and Pull Requests are welcome there too :smile:
