### ISSUE TITLE
extra_response_fields should be after (not before) any on_inserted hooks on POST

### ISSUE THREAD

**Issue by kenmaca** [pyeve/eve#711]
Currently, `extra_response_fields` are processed after `on_insert` hooks are complete but before any `on_inserted` hooks.

It would be intuitive and great to have `extra_response_fields` processed after both of these hooks are complete - in case we changed something during `on_inserted`.

**Comment by nicolaiarocci** [comment]
Hello and thanks for the suggestion. That's tricky though, as callbacks which are hooked to `on_inserted` are guaranteed to receive the complete response payload, so it can be eventually edited before it is sent over the wire. Should we move the hook before response marshalling, callbacks would loose that guarantee.
