### ISSUE TITLE
Media field showing only ObjectId instead of its actual data when accessed via an alternate endpoint

### ISSUE THREAD

**Issue by kenmaca** [pyeve/eve#719]
Suppose I have an `users` endpoint that looks like:

```
users = {.., 'schema': {
    'photo': {
        'type': 'media'
    }
}}
```

.. and an alternate endpoint named `profiles` that looks like:

```
profiles = {.., 'datasource': {
    'source': 'users',
    'projection': {
        'photo': 1
    }
}}
```

The `photo` field is returned properly (showing binary data) via `users`, but is returned as its `ObjectId` instead in the `profiles` endpoint.

**Comment by nicolaiarocci** [comment]
Hello, I was not able to reproduce this with v0.6. Could you verify that it is still an issue with latest version?

**Comment by kenmaca** [comment]
Thanks for looking into this. Yes, I can confirm that I am on 0.6 (directly from the master branch).

I'll have a look again and post a follow up with more details.
