### ISSUE TITLE
documentation of event hook

### ISSUE THREAD

**Issue by antoine-gallix** [pyeve/eve#725]
The documentation states that on_post_POST_<resource> callback accepts 3 arguments.
http://python-eve.org/features.html#event-hooks
However, it seems that DELETE callback are called with only 2 arguments, resource and request, instead of resource, request and payload.
It seems logic but it is not documented

A table of existing request event hooks, with names and signature, like the database event hooks table below would be helpful.

**Comment by nicolaiarocci** [comment]
Thanks for reporting this. Would you (or anybody else reading this) be willing to help by submitting a PR to update the docs?
