### ISSUE TITLE
Secondary endpoint on a datasource not returning any (non-eve) record data

### ISSUE THREAD

**Issue by milutz** [pyeve/eve#733]
I think I'm seeing a broader version of the problem kenmaca saw in issue #719.  

I have two endpoints to the same data source.  "sessions" and "last" (which includes a sort order and don't allow item lookup). 

My secondary endpoint ("last") returned record data in eve 0.5.3 and 0.6-dev0, but on a new host I've just loaded with eve 0.6, "last" does't returning any of record content, just _id and the eve managed fields (_created, _etag, and _updated).

I downgraded to eve 0.5.3 on the troublesome host and the secondary endpoint started returning record data as I expected.

My endpoints are as follows:

```
    'sessions': {'datasource': { 'source' : 'blah',},
                  'url':'<regex("[\w]+"):camera_id>/sessions',
                  'allow_unknown' : True, 
                  'schema' : sessions_schema,
                  'cache_control' : 'no-cache',
                  'item_methods': ['GET', 'PATCH'],
                  },
    'last':       {'datasource': { 'source' : 'blah',
                                  'filter' : { 'session_id': {'$exists': True}},
                                  'default_sort': [('_id', -1)],
                                  },
                   'url':'<regex("[\w]+"):camera_id>/sessions/last', 
                   'cache_control' : 'no-cache',
                   'resource_methods' : ['GET'],
                   'item_lookup': False,
                   },
```

**Comment by nicolaiarocci** [comment]
Hello, did you try with current dev branch? I ask because I pushed an update last week which also deals with datasource projections. It might have impact on your issue as well.

**Comment by milutz** [comment]
I have not.  Will update if I complete that test.
