### ISSUE TITLE
Need update method which can update multiple documents in Mongo

### ISSUE THREAD

**Issue by sivakuna-aap** [pyeve/eve#737]
The `eve.io,mongo.mongo.Mongo.remove()` is capable of removing set of documents from a Mongo Collection. Similarly we need update() which can update multiple documents matching query.

At present, the update method in `eve.io.mongo.mongo.Mongo.update()` forces to use only primary key (`_id`). Although this is true as per REST API guidelines but there will be some scenarios where multiple update is necessary. PyMongo supports updating multiple documents but eve misses it.

**Comment by nicolaiarocci** [comment]
In theory we could open up the collection endpoint for some sort of "bulk" `PUT` and even `PATCH` support, but that would require quite some work and also, as you mention, I am not sure it would adhere to sound REST principles (probably so, but I'd want to investigate it a little further). 

You can achieve your goal by updating every document individually of course, which I understand is not very practical in your use case. I'm keeping this ticket open for the time being, in case someone wants to give a shot at it and submit a PR.
