### ISSUE TITLE
JSON API I/O

### ISSUE THREAD

**Issue by anthony-arnold** [pyeve/eve#821]
I'm working with an [API Consumer](http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html) which expects API output to conform to the [JSON API](http://jsonapi.org) specification. While the HATEOAS output from Eve is close, it's not quite compatible. This can be worked around either on the server (using `on_fetched_item` or `on_fetched_resource` to inject fields to the response), or on the consumer-side by providing a mapping of Eve-to-JSON API. However, this seems like too much work being done by either side.

I'm suggesting a new feature which would allow you to configure an API for JSON API-compatible I/O. The proposed feature would work like this:
1. A new configuration keyword `JSON_API` that, when true, enables JSON API requests.
2. When `JSON_API == True`, the following config values are set as defaults:
   - ID_FIELD = "id"
   - LINKS = "links"
   - ITEMS = "data"
   - META = "meta"
   - ISSUES = "errors"
   - STATUS = "status"
3. When an incoming request has the header `Content-Type: application/vnd.api+json`, this activates JSON API handling iff `JSON_API == True`.
4. The following changes to API response objects are made when JSON API handling is activated.
   - An item's field data are placed in an `attributes` map inside the resource object, with the exception of "id", which stays at the top level of the item object.
   - A new field, "type", at the top level of the item object is added to the response payload. This is set to the resource name.
   - The `links` section of output will be made JSON API-compatible. At the moment this just looks like wrapping the "title" key in a "meta" object.
   - Any embeddable data relation will be returned in a [relationships](http://jsonapi.org/format/#document-resource-object-relationships) object. 
   - Endpoints will accept the [include](http://jsonapi.org/format/#fetching-includes) query string key, similar to how embedded works now. However, included object will be returned in an `included` object at the top level of the response object, instead of embedded in the items.
   - Endpoints will accept the [fields](http://jsonapi.org/format/#fetching-sparse-fieldsets) query string key, similar to how projection works now.
5. For [CRUD](http://jsonapi.org/format/#crud) operations, a similar format to the above will be accepted.
6. Compatible [error responses](http://jsonapi.org/format/#errors).

This doesn't cover the JSON API spec entirely, but I think it's a good start toward supporting the minimal requirements.

**Comment by AduchiMergen** [comment]
:+1:

**Comment by nicolaiarocci** [comment]
Well this would of course be a very nice feature to have. I'm worried however that it would significantly  increase code complexity and maintenance burden. I'm wondering if it could be contributed as an extension (Flask blueprint) named, say, Eve-JSONAPI?

**Comment by nicolaiarocci** [comment]
And also, are you volunteering for the the implementation? :smile:

**Comment by harryjubb** [comment]
+1 for this; is anybody implementing it already? If so, or not, how can I help?

My main motivation is to get from MongoDB into [Ember Data](https://github.com/emberjs/data), I'm not having any luck getting any JSONAPI compatible servers working properly, while Eve works so beautifully(!) but is just without JSONAPI.

**Comment by ymahnovskyy** [comment]
+1
We also are interested in this feature.

**Comment by aguirrel** [comment]
+1 Hi guys, somebody is working on it?

**Comment by riazjahangir** [comment]
+1 I haven't seen any official work on this, but for anyone who ends up on this page, here is a minimal solution I used to modify the response data according to JSON-API. This is not comprehensive. The advantage here over using the database fetch hooks, is we can handle the `_error` response as well.
```
from flask.wrappers import Response
import json

class JsonAPIResponse(Response):
    resource_name = None

    def set_data(self, value):
        response = json.loads(value)

        jsonapiresponse = {}
        if '_items' in response:
            jsonapiresponse['data'] = [self.convert_obj(item, JsonAPIResponse.resource_name)
                                       for item in response['_items']]
        elif '_id' in response:
            jsonapiresponse['data'] = self.convert_obj(response, JsonAPIResponse.resource_name)
        if '_error' in response:
            jsonapiresponse['errors'] = self.convert_err(response['_error'])
        response.clear()
        response.update(jsonapiresponse)

        super().set_data(json.dumps(jsonapiresponse))

    def convert_obj(self, eveobject, resource_name):
        """Convert Eve's default object format to one compatible with JSON-API"""
        top_level_eve_fields = ['_id']
        jsonapiobject = {
            'id': eveobject['_id'],
            'type': resource_name
        }
        attributes = {}
        for k in eveobject:
            if k not in top_level_eve_fields:
                attributes[k] = eveobject[k]
        jsonapiobject['attributes'] = attributes
        return jsonapiobject

    def convert_err(self, eveerror):
        """Convert Eve's _error object to JSON-API error object"""
        errors = []
        errors.append({
            'detail': eveerror['message'],
            'status': str(eveerror['code']),
        })
        return errors
```

Then in `run.py`:
```
    def monitor_GET_targets(resource, request, lookup):
        JsonAPIResponse.resource_name = resource

    ....
    app = Eve()
    app.response_class = JsonAPIResponse
    app.on_pre_GET += monitor_GET_targets
```

**Comment by nicolaiarocci** [comment]
Very nice. Would you be willing to submit this as a PR in the Snippets sections of the docs?

**Comment by aguirrel** [comment]
Hi guys,

Thanks @riazjahangir! I did my own solution, pretty simple but works pretty well with [Ember Data](https://github.com/emberjs/data).  You can do all actions (create, delete and update), not only get.

**IMPORTANT NOTE: is not a JSONAPI compliant, just a very easy way to connect Eve and [Ember Data](https://github.com/emberjs/data)!**

Background: when you use ember-data, the belongsTo and hasMany works in a specific way, when you add, delete or update a hasMany relationship and you save the model, the container class (ex. client) will not send the items id (ex. invoices).  But when you save invoices contained in the client, they will update the client belongsTo relationship.  So, main problem here is that you have to get all invoices ids when you get the client using json api.

In python `__init__.py`

```python
def add_has_many(resource, response):
    for has_many in settings.DOMAIN[resource].get('has_many', []):
        _id = response['_id']
        f = {has_many['source_id']: str(_id)}
        has_many_ids = [str(x['_id']) for x in list(getattr(mongo.db, has_many['source_collection']).find(f))]
        response[has_many['property']] = has_many_ids
        # NOTE: If you have many items, you can use URL instead array of ids.  
        # In this case use 'links' instead of the property
        # response['links'] = { "items": '/items?where={"_id":{"$in": %s}}' % json.dumps(items_ids)}

def add_has_many_in_list(resource, response):
    for item in response['_items']:
        add_has_many(resource, item)

app = Eve()
app.on_fetched_item += add_has_many
app.on_fetched_resource += add_has_many_in_list
```

In `settings.py` file, you have to define the `'has_many'` property, for example, client has many invoices.  I use` 'allow_unknown': True` for a fast startup.

```python
DOMAIN = {
    'clients': {
        'allow_unknown': True,
        'has_many': [{'property': 'invoices', 'source_collection': 'invoices', 'source_id': 'client'}]
    },
    'invoices': {
        'allow_unknown': True,
        'schema': {
            'sendDate': {
                'type': 'datetime',
                'required': False,
                'nullable': True
            },
            'dueDate': {
                'type': 'datetime',
                'required': False,
                'nullable': True
            }
        }
    }
}
```

OK! Now let's work with Ember App now!

Let's create an adapter and a serializer for this:

```bash
ember g adapter application
ember g serializer application
```

In file `app/adapters/application.js`

```javascript
import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend({
    host: 'https://your-eve-host',
    headers: {
        'Content-Type': 'application/json'
    },
    normalizeErrorResponse(status, headers, payload) {
      let error = payload._error;
      return [
        {
          detail: error.message,
          status: error.code,
          code: error.code
        }];
    }
});
```

In file `app/serializers/application.js`

```javascript
import DS from 'ember-data';
import Ember from 'ember';

export default DS.JSONSerializer.extend({
  primaryKey: '_id',
  normalizeArrayResponse(store, primaryModelClass, payload) {
    Ember.assign(payload, payload._items);
    payload.length = payload._items.length;
    payload.meta = payload._meta;
    return this._super(...arguments);
  }
}); 
```

Now, create models as always! Here some example:

```bash
ember g model client
ember g model invoice
```

File `app/models/client.js`

```javascript
import DS from 'ember-data';

export default DS.Model.extend({
  fullName: DS.attr(),
  email: DS.attr(),
  photo: DS.attr(),
  invoices: DS.hasMany('invoice', {async: true})
});
```

File `app/models/client.js`

```javascript
import DS from 'ember-data';
import Ember from 'ember';

export default DS.Model.extend({
  client: DS.belongsTo('client', {async: true}),
  items: DS.attr( { defaultValue() {return []; }}),
  sendDate: DS.attr('gmt'), // NOTE: You need to use toGMTString to get the correct date in MongoDB
  dueDate: DS.attr('gmt'),
  status: DS.attr()
});
```

And, finally, the gmt transformation in case you want to use dates:

`ember g transform gmt`

Now edit the file `app/transforms/gmt.js`

```javascript
import DS from 'ember-data';

export default DS.Transform.extend({
  deserialize(serialized) {
    return new Date(serialized);
  },

  serialize(deserialized) {
    return deserialized ? deserialized.toGMTString() : null;
  }
});
```
