### ISSUE TITLE
Demo fails

### ISSUE THREAD

**Issue by KevinBurton** [pyeve/eve#826]
I am just starting to use Eve and right off the bat I get a syntax error:

H:\eve-demo>python run.py
Traceback (most recent call last):
  File "run.py", line 19, in ?
    from eve import Eve
  File "H:\eve-demo\eve__init__.py", line 87, in ?
    from eve.flaskapp import Eve  # noqa
  File "H:\eve-demo\eve\flaskapp.py", line 152
    self.media = media(self) if media else None
                              ^
SyntaxError: invalid syntax

Ideas?

**Comment by nicolaiarocci** [comment]
On which version of Eve are you? Also, what is `eve__init__.py`? And, that `from eve.flaskapp import Eve` line seems wrong. Did you try to basic [quickstart](http://python-eve.org/quickstart) guide first, just to get your bearings?
