### ISSUE TITLE
Eve() should not have creation dependencies

### ISSUE THREAD

**Issue by txomon** [pyeve/eve#828]
I have realized that I cannot test my eve/flask functions because on object creation, it tries to connect to the mongodb.

The problem is that indexes are created on object creation, and not on eve app run (database connection should only be triggered when running the app)

```
Traceback (most recent call last):
  File "/.../app/__init__.py", line 15, in <module>
    app = Eve(settings=settings)
  File "/.../libraries/eve/eve/flaskapp.py", line 171, in __init__
    self.register_resource(resource, settings)
  File "/.../libraries/eve/eve/flaskapp.py", line 839, in register_resource
    create_index(self, resource, name, list_of_keys, index_options)
  File "/.../libraries/eve/eve/io/mongo/mongo.py", line 905, in create_index
    conn = pymongo.MongoClient(host_and_port)
  File "/.../pymongo/mongo_client.py", line 425, in __init__
    raise ConnectionFailure(str(e))
pymongo.errors.ConnectionFailure: [Errno 111] Connection refused
```

I haven't been able to speak with any of the maintainers, so i don't know how to proceed. My first guess would be to move the index creation somewhere else. But you probably know about a better solution

**Comment by nicolaiarocci** [comment]
As a workaround you could experiment with only adding `mongo_indexes` to your resource schema if not running a test. It's just the index creation that is performed at app initialisation. Long term, I guess we could look into moving index creation at first endpoint request, or something like that.

**Comment by Amedeo91** [comment]
Personally I think index creation should be triggered at installation time. What I want to say, it is that I will make much more sense to create the indexes before the Flask app is even started, eventually by changing the start-up script.
