### ISSUE TITLE
Duplicate resources as a feature

### ISSUE THREAD

**Issue by sunbit** [pyeve/eve#838]
Hello,

i was thinking of implement a duplication feature on one resource i'm developing, and i was thinking of something like:

POST /resource?source=id_of_original_resource

Is there any way to do something similar to this currently with eve? Is this something you think it could be useful to be included on eve as a feature? 

Thank you

**Comment by nicolaiarocci** [comment]
Honestly I suspect this feature is really hard to pull off in a proper, RESTful way. Also, it seems of limited use since you can already POST the same object multiple times as long as the ids are being created by the server.

**Comment by sunbit** [comment]
A way to avoid the double GET-POST request on the client side is just what i had in mind. Nevertheless I understand and share your concern about finding a RESTful way to do it, i'm only pretending to find consensus, if you think it would be useful/possible.

If you happen to find the time to look at it, after doing a littlle research i found there's currently two approaches for doing this used by Amazon & Google, (and also some people looking for the same feature), discussed on the following links:

http://stackoverflow.com/questions/3017143/restful-copy-move-operations
http://stackoverflow.com/questions/18755220/what-is-the-restful-way-to-represent-a-resource-clone-operation-in-the-url

Thank you

**Comment by nicolaiarocci** [comment]
Thanks for the research. [This](https://stackoverflow.com/a/14982093/323269) approach seems interesting and actually, even now, you could probably wire up a Flask endpoint to support it. The [Amazon](https://stackoverflow.com/a/18755334/323269) way is also interesting though.
