### ISSUE TITLE
CORS and response abort

### ISSUE THREAD

**Issue by mohierf** [pyeve/eve#839]
This issue is not made to report a bug but simply to feedback on problems I had to make Eve correctly manage CORS when I need to abort a request and send a custom response ...

If you wish to abort a request, you think you should use the standard `abort(make_response( ...` that is commonly used with Flask application, but this is correct only if you do not need to use CORS ! 

 This, because you do not use the reponse built by Eve and then you do not add the CORS headers in the response sent to the client ...

 I managed to use something like this: 

```
from flask import abort
from eve.render import _prepare_response
def on_insert_test(items):
    for index, item in enumerate(items):

        abort(_prepare_response(
                'test',
                {"_status": "KO", "content": "Error message ..."},
                status=412
            ))
```

It may be interesting that Eve provide its own abortion method ? At least, it would have saved to me a full day of searching why my cross-domain were sometimes accepted and sometimes refused :smile:

**Comment by nicolaiarocci** [comment]
Nice job on importing `_prepare_response` by the way. As you can guess by its name, I did not anticipate someone might want to use it outside of eve core.  

This has been brought up by somebody else in the past, and I find the idea interesting.  Maybe somebody is willing to work on it?
