### ISSUE TITLE
Following Quickstart Guide, The server freezes up when requesting the /people URL

### ISSUE THREAD

**Issue by ben174** [pyeve/eve#849]
This is very odd, and I've tried it on two machines. 

I create a brand new virtualenv, source it, then `pip install eve`.

Then I create a `run.py`:

```
from eve import Eve
app = Eve()

if __name__ == '__main__':
    app.run()
```

and a `settings.py`:

```
DOMAIN = {'people': {}}
```

Then I `python run.py` and `curl http://127.0.0.1:5000` and it returns as expected:

```
{"_links": {"child": [{"href": "people", "title": "people"}]}}%
```

But when I `curl http://127.0.0.1:5000/people` it locks up, returning nothing. After several seconds, it seems to time out and return a 500, and the console output is:

```
127.0.0.1 - - [31/Mar/2016 15:47:35] "GET /people HTTP/1.1" 500 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 59848)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by nicolaiarocci** [comment]
Hello, what happens if you run Eve with `app.run(threaded=True)`?

**Comment by ben174** [comment]
Tried this, same issue.

**Comment by nicolaiarocci** [comment]
I am afraid I'm out of ammo here. A [quick search](error: [Errno 32] Broken pipe) suggests that this happens when multiple requests hit the development server (like app.run, don't use it in production) and the first request has not been processed yet. This does not seem to be your case (unless something else is happening between the curl requests of course). I tried a clean pip install and copy & pasted your code: it works fine on my end.

If you find a way out please let us know: it might be useful to someone else.

**Comment by rushproject** [comment]
Similar behavior here (server freezes up when requesting the /people), fixed by installing and launching mongod.

**Comment by nicolaiarocci** [comment]
Ah yes of course. Eve needs a running mongod (the mongo server) instance.

Il giorno gio 7 apr 2016 alle ore 19:47 Alex Pavlov <
notifications@github.com> ha scritto:

> Similar behavior here (server freezes up when requesting the /people),
> fixed by installing and launching mongod.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/nicolaiarocci/eve/issues/849#issuecomment-207023431>
>
-- 
Nicola Iarocci
http://nicolaiarocci.com

**Comment by ben174** [comment]
Ah! That makes sense, thanks so much! Mind if I submit a patch that will spit out a warning if it doesn't see mongod?

**Comment by nicolaiarocci** [comment]
Sure go ahead
