### ISSUE TITLE
Restructure request parsing in method handling

### ISSUE THREAD

**Issue by NotSpecial** [pyeve/eve#854]
Currently the request object is needed in every layer of eve, meaning in post_internal (etc.) as well as the eve data layer.

This makes all those functions require a request context and the situation is as follows:

_require request context:_
- `get`, `post`, `patch`, `put`, `delete`
- `get_internal`, `post_internal`, `patch_internal`, `put_internal`, `delete_internal`
- eve data layer

_require app context:_
- db connection (e.g. `app.data.driver.db`)

This leads to two problems:
### 1. Using internal methods in existing request have side effects

Since the internal methods parse the request (and I am unable to interfere without changing the original request), e.g. a get_item internal will always inherit values like "if_modified_since" from the original request, even if I don't want that in my internal request.

The only way to get around this is using the eve data layer or the database connection directly , but this way no hooks will be triggered.

I would love to be able to to use the *_internal methods to avoid repeating myself or forgetting to include hooks in some places and without having to modify the original request (since its easy to forget bringing it back to its original state)
### 2. Extra modules can't use internal methods without workarounds

In our current project we have a small LDAP connector which should synchronize our data every night or so. Since all this happens internally, I want to bypass request details and use the `*_internal` methods if possible.

For my use case I can easily create a `app_context` to work with the app, but I don't have a request environment.
Unfortunately I can only use the db connection now since all eve methods require a `request_context`.

A workaround would be using a `test_request_context`, but as the name implies it is intended for testing and I rather would not do that. But I believe this could be fixed easily.
### Possible Solution:

I have thought a while about how this can be solved and also looked into the diskussion in #74 and would propose the following structure:

_require request context:_
- `get`, `post`, `patch`, `put`, `delete`

_require app context:_
- `get_internal`, `post_internal`, `patch_internal`, `put_internal`, `delete_internal`
- eve data layer
- db connection (e.g. `app.data.driver.db`)

This means the request parsing would exclusively happen in the get (etc.) methods and the results passed to the lower layers.

I agree with your point in #74 that just passing lots of arguments around doesn't help to make it very clear.

I would solve this passing a `ParsedRequest` to all `*_internal` functions as well as to the data layer (as it's already happening for the `find_one` method).
But to make clear that it can also be used without a active request I would rename it to `FilterOptions` and give it an `__init__` function to make it easy to create. The `parse_request` would now happen in the top layer functions ( `get`, `post`, `patch`, `put`, `delete`) to create a `FilterOptions` instance that will be passed on. (Or can be created easily yourself if there is no request around)

I think this solution doesn't really change the data flow through eve, but rearranges it just a little bit to allow the following without any workarounds:
- use internal methods without interference from external filters
- use internal methods just with an `app_context`

I would gladly give this a shot and send you a pull request, but I would like to know what you think about the issue first.

Thanks in advance (as well for all the great work you put into Eve so far!)

**Comment by nicolaiarocci** [comment]
Hello!

Well clearly you put a lot of thought into this, and I thank you for that. I like your plan and would be more than willing to review your pull request on the subject.
