### ISSUE TITLE
Allow developers to define logic with the request

### ISSUE THREAD

**Issue by huiyiqun** [pyeve/eve#860]
Eve is cool to define CRUD web service. but it's also common to do something like this:

``` python
def echo(name):
    return {"msg": "Hello {}".format(name)}
```

or

``` python
def do_something(arg):
    ret = fire_backend_task(arg)
    return {"result": ret}
```

As Eve is based on flask, we could define route directly, but eve has implemented boilerplate
such as:
- auth
- parse request
- form response
- event hook
- CORS

Is there any plans to expose some inner utils so that developers could:

``` python
@app.route('/hello/<user>', methods=['GET'])
@eve.utils.require_auth(auth=MySupperCoolAuth, allowed_role=['admin'])
def hello(user):
    req = eve.utils.parse_request();
    return eve.utils.form_response("hellow {}".format(user), 200);
```

or allow user to override inner logic so that developers could:

``` python
do_something(payload, header):
    return fire_backend_task(payload)

app.override_POST_task = do_something
```

**Comment by huiyiqun** [comment]
The main point is that developers could write flexible logics with the same interface(or IO) with Eve-defined endpoint.

**Comment by nicolaiarocci** [comment]
Yes, see [Custom endpoint handlers with Eve](http://nicolaiarocci.com/building-custom-endpoint-handlers-with-eve/). I should probably add this stuff to the main docs.

**Comment by huiyiqun** [comment]
Actually, I have read this before.

But I think it's better if eve could provide some utils to custom endpoint:

 * auth (`requires_auth` is good but how to configure allowed_roles?)
 * parse request (`eve.methods.common.payload` is good but requires documentation)
 * form response(`eve.render.send_response` is good but requires documentation)
 * CORS(it's handled in `eve.render.send_response` but should custom endpoint also have a resource?)
 * validation(`app.validator` is good but requires documentation)

There is another choice that allowed developers to override eve.methods.[get, getitems,...]

**Comment by huiyiqun** [comment]
it seems `requires_auth` decorated functions must include resource in args or kwargs, so the example in this [link](http://nicolaiarocci.com/building-custom-endpoint-handlers-with-eve/) does not work.

**Comment by antomor** [comment]
Hi @nicolaiarocci , I encountered the same problem found by @huiyiqun .
No way to pass the resource to `requires_auth` function, so I am not able to fully configure authentication on a custom endpoint so as I can on resource endpoint.
Any news on that?

Thank you in advance.
