### ISSUE TITLE
Feature Request embedded aggregations

### ISSUE THREAD

**Issue by s3ppo** [pyeve/eve#882]
Hi,

would be nice to have embedded aggregations.
any chance to get this?

LG
Harald

**Comment by nicolaiarocci** [comment]
Could you please elaborate on that? Maybe add an example of how it would work.

**Comment by s3ppo** [comment]
hi nicola,

i can try it...
actually i can embedd ressources from other collections by:
 DOMAIN = {
     'emails': {
         'schema': {
             'author': {
                 'type': 'objectid',
                 'data_relation': {
                     'resource': 'users',
                     'field': '_id',
                     'embeddable': True
                 },
             },
             'subject': {'type': 'string'},
             'body': {'type': 'string'},
         }
     }

what i mean is perhaps something like this:
 DOMAIN = {
     'emails': {
         'schema': {
             'author': {
                 'type': 'objectid',
                 'data_relation': {
                     'resource': 'users',
                     'field': '_id',
                     'embeddable': True
                     'aggregation_field': sum_of_all_users     <-- this field would be appended in the output structure
        'aggregation': {
            'pipeline': [
                {"$group": {"_id": "$sum_of_all_users", "count": {"$sum": "$value"}}},
                {"$sort": SON([("count", -1), ("_id", -1)])}
            ]
        }
                 },
             },
             'subject': {'type': 'string'},
             'body': {'type': 'string'},
         }
     }

sry the example is just a short copy&paste.. from the eve docu.. i would have an much more complex use case ;-)

LG
Harald
