### ISSUE TITLE
Long TTFB

### ISSUE THREAD

**Issue by harryjubb** [pyeve/eve#883]
Hi,

I'm having a problem with an Eve API (v0.6.4 from pip) I'm serving.

API requests (GET only at the moment) are taking a long time to complete. Using the Chrome dev tools with the cache disabled, I've determined that a huge amount of time is spent waiting for data (Time To First Byte):

![egfr_-_cosmic-3d](https://cloud.githubusercontent.com/assets/4588417/16733923/705f9d9c-477b-11e6-8de2-c2874c8ebf97.png)

The same happens when using `curl`:

``` bash
time curl http://localhost:5000/api/dbcollection/EGFR &> /dev/null 

real    0m5.826s
user    0m0.006s
sys     0m0.016s
```

The database query runs in MongoChef in **309 ms**.

I am struggling to figure out why the Eve API is taking so much longer, so far a colleague and I have tried/found out the following:
- Tested in the Flask dev server with `app.run(threaded=True)` (and with both `debug=True` and `debug=False`), and via Tornado, gevent servers, and when deployed on Apache using `mod_wsgi`: all have the same issue
- While the data returned are large (9.2 MB uncompressed), the transfer time is clearly minimal as shown by the Chrome dev tools above, the ~5 seconds are before any data are sent, not the transfer itself
- Was originally ~8 seconds TTFB for the EGFR endpoint, down to ~5-6 seconds when Eve schema validation is globally disabled (`TRANSPARENT_SCHEMA_RULES = True`)
- Adding/removing gzip compression on the server doesn't affect TTFB; the download size and time become smaller but are still eclipsed by the same TTFB time
- Using a `?where=` query instead of an `additional_lookup` endpoint does not make a difference
- The solution posted here http://werkzeug.pocoo.org/docs/0.11/serving/#troubleshooting, removing the `::1` line from `/etc/hosts`, did not make a difference
- Crudely using Activity Monitor (OS X) to watch the CPU load while `curl`ing shows that the time is spent in Python, ~100% CPU, ~280MB of memory used.
- But profiling with `python -m cProfile -s cumtime run.py > log` while `curl`ing doesn't reveal any insights into where the time is spent:

```
         89197 function calls (86477 primitive calls) in 8.446 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.001    0.001    8.446    8.446 run.py:1(<module>)
        1    0.000    0.000    8.288    8.288 flaskapp.py:183(run)
        1    0.000    0.000    8.288    8.288 app.py:722(run)
        1    0.001    0.001    8.288    8.288 serving.py:560(run_simple)
        1    0.000    0.000    8.281    8.281 _reloader.py:237(run_with_reloader)
        1    0.000    0.000    8.281    8.281 _reloader.py:90(restart_with_reloader)
        1    0.000    0.000    8.281    8.281 subprocess.py:514(call)
        2    0.000    0.000    8.280    4.140 subprocess.py:473(_eintr_retry_call)
        1    0.000    0.000    8.278    8.278 subprocess.py:1379(wait)
        2    8.278    4.139    8.278    4.139 {posix.waitpid}
        4    0.004    0.001    0.131    0.033 __init__.py:11(<module>)
        2    0.003    0.001    0.077    0.038 __init__.py:16(<module>)
    12/10    0.003    0.000    0.043    0.004 {__import__}
        7    0.002    0.000    0.043    0.006 __init__.py:1(<module>)
        1    0.001    0.001    0.039    0.039 _compat.py:3(<module>)
        1    0.000    0.000    0.037    0.037 __init__.py:8(<module>)
      211    0.001    0.000    0.034    0.000 re.py:230(_compile)
        1    0.000    0.000    0.034    0.034 __init__.py:39(<module>)
       93    0.000    0.000    0.034    0.000 re.py:192(compile)
        1    0.002    0.002    0.034    0.034 flaskapp.py:11(<module>)
[...rest all low millisecond...]
```

I'm struggling to figure out why it's taking so long for each request to respond. It seems to scale with data size: For example:
- A request for an endpoint that returns 1.5 MB of data results in:

```
Waiting (TTFB) - 725.31 ms
Content Download - 27.88 ms
```
- A request for an endpoint returning 129 KB of data results in

```
Waiting (TTFB) - 72.76 ms
Content Download - 0.72 ms
```

The outcome is that the web app I am developing can be slow to load, and this seems to be the bottleneck. 

Any thoughts, ideas, and suggestions on how to solve this would be much appreciated.

Many thanks,

**Comment by nicolaiarocci** [comment]
Is pagination enabled? If so, the `count()` operation performed in order to compute the page subset can greatly impact performance. I'm pushing a new ``OPTIMIZE_PAGINATION_FOR_SPEED`` which should really help especially if you have large collections. See #944, where a real-life use case went from 8s to 134ms on a single request.

**Comment by harryjubb** [comment]
I have pagination disabled on those endpoints because I need all the data, but looking at the output of `mongotail`, there's clearly a `count` happening at some point, and it does look like it's holding up the request:

```
2016-12-18 12:07:26.029 QUERY     [collection] : {"search": "item"}. 101 returned.
2016-12-18 12:07:29.506 COUNT     [collection] : {"search": "item"}
```

I'm on 0.6.4 but can try in 0.7 and see what happens.

**Comment by nicolaiarocci** [comment]
Yes please, do so.
