### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by cburchert** [pyeve/eve#949]
It seems to me eve does not handle timezones in a consistent way. For example when implementing a custom MediaStorage class one has to give the upload_date of a file with a timezone. Data coming in from the outside in requests are parsed with strptime, which gives a local time without a timezone.
In general everything coming from the data layer has a timezone attached, things from the outside do not. Comparing two dates with and without a timezone gives an exception, which has lead to bugs more than one time in our projects.

This problem is very bad in validators. For example in one of our projects we implemented a later_than validator, which can check, that one date in an object is later than another date. However this is not trivial due to timezones:

* In a post request both datetime objects have no timezone, as they come from the request payload.
* In a patch request any of the datetime objects may come from the data layer, so something has to be converted.

Developers need to be aware of the internal structure of eve just to implement simple validators. As I see it there are two solutions:

* Attach timezones everywhere. This might be as simple as changing the str_to_date function in eve.utils, which parses incoming request data(Though I have not checked the consequences).
* Use local times everywhere. This can be achieved with a PyMongo option. That way no timezones come from mongo and we have naive times everywhere.

Both solutions probably create further problems, as eve converts times at several locations. I think using timezones is cleaner.

What do you think? Should I try to implement something and make a pull request?

**Comment by tyomo4ka** [comment]
@Leonidaz0r 

That make sense. I'm also having this issue with timezones. `strptime` function ignores timezone, so you can not use time with timezone in payloads. And in my app cause clients send their local time so it must be with time zone attached, I don't want to force them to convert in UTC.

I agree here should be consistent approach across application. But I believe some people would prefer to use local time when other would like to use timezones. In my opinion we need a configuration setting for this and it should be in sync with PyMongo `tz_aware` option in MongoClient.

I will try to implement a PR for this.

http://stackoverflow.com/questions/3305413/python-strptime-and-timezones
