### ISSUE TITLE
geo indexes while defining type as point

### ISSUE THREAD

**Issue by ankur777** [pyeve/eve#958]
In my schema I have defined location point with mongodb as backend database.
But when I checked indexes I am not able to find same

> db.property.getIndexes()
[
        {
                "v" : 1,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "demo-sa-eve.property"
        }
]

Also, the $near query gives following error
location maxdist=1000 isNearSphere=0

Does we need to create indexes separately. What I am doing wrong here

**Comment by Martin456** [comment]
Hello Ankur,
Eve doesn't create indexes for you automatically as stated [here](http://stackoverflow.com/questions/32864091/geojson-python-eve-example).
