### ISSUE TITLE
has anyone had any success in utilizing flask-security as a user/authentication manager for eve 

### ISSUE THREAD

**Issue by nikitph** [pyeve/eve#965]
i have a web app which uses flask-security. now i want to build a rest api on top of it and use the users from web app

here is what i am trying 

import time

import bcrypt
from eve import Eve
from eve_mongoengine import EveMongoengine
from eve.auth import BasicAuth

# init application
from flask.ext.security import Security, MongoEngineUserDatastore
from public.models import *
from user.models import User,Role
from flask.ext.mongoengine import MongoEngine

MONGODB_SETTINGS = {

    # 'MONGO_HOST': 'localhost',
    #     'MONGO_PORT': 27017,
    #     'MONGO_USERNAME' : None,
    # 'MONGO_PASSWORD': None,
    'MONGO_DBNAME': 'houzee',
    'X_DOMAINS': '*',
    'ALLOW_OVERRIDE_HTTP_METHOD':'true',
    'JSON_SORT_KEYS	':'true',
                   'DOMAIN': {'resident': {}}
}

class MyBasicAuth(BasicAuth):
    def check_auth(self, username, password, allowed_roles, resource,
                   method):
        return username == 'admin' and password == 'secret'

app = Eve(settings=MONGODB_SETTINGS, auth=MyBasicAuth)
db=MongoEngine()
db.init_app(app, config=MONGODB_SETTINGS)
user_datastore = MongoEngineUserDatastore(db, User, Role)
security = Security(app, user_datastore)
# init extension
ext = EveMongoengine(app)
# register model to eve
ext.add_model(Resident)
ext.add_model(Township)

# let's roll
app.run(host='127.0.0.1', port=8001)

the app runs without problems but as soon as i send in a request from postman, i get a 500. i dont know any more error details.

**Comment by Zyclotrop-j** [comment]
I got it to work:
`from flask_cors import CORS, cross_origin
from flask_security.core import current_user
from flask_principal import Identity, Permission, RoleNeed
from flask_security.core import current_user
from contextlib import contextmanager
from flask_login import user_logged_in, user_logged_out

app = Eve(auth=Auth)
CORS(app)

app.config['DEBUG'] = True
app.config['SECRET_KEY'] = 'super-secret'
app.config['WTF_CSRF_ENABLED'] = False

db = MongoEngine(app)

class Role(db.Document, RoleMixin):
    name = db.StringField(max_length=80, unique=True)
    description = db.StringField(max_length=255)

class User(db.Document, UserMixin):
    email = db.StringField(max_length=255, unique=True)
    password = db.StringField(max_length=255)
    active = db.BooleanField(default=True)
    confirmed_at = db.DateTimeField()
    roles = db.ListField(db.ReferenceField(Role), default=[])
    last_login_at = db.DateTimeField()
    current_login_at = db.DateTimeField()
    last_login_ip = db.StringField(max_length=255)
    current_login_ip = db.StringField(max_length=255)
    login_count = db.IntField()

user_datastore = MongoEngineUserDatastore(db, User, Role)
security = Security(app, user_datastore)

if __name__ == '__main__':
    app.run(ssl_context='adhoc')`

Note that eve is not managing the user or role.
Also note that this is only working under python2 for me, python3 gives me ominous errors.
