### ISSUE TITLE
Documented config params do not exist in code

### ISSUE THREAD

**Issue by gmargari** [pyeve/eve#972]
To get all params from http://python-eve.org/config.html:
```python
# eve-get-config-params.py
import lxml.html, requests, re
page = requests.get('http://python-eve.org/config.html')
tree = lxml.html.fromstring(page.content)
divs = tree.xpath('//tr/td[1]/tt[@class="docutils literal"]/span[@class="pre"]/text()')
divs = [ div for div in divs if re.match("^[A-Z_]*$", div) ]
print("\n".join(divs))
```

Find all config params that do not exist in the code of the latest version of Eve:
```bash
git clone https://github.com/nicolaiarocci/eve.git
for param in `python eve-get-config-params.py`; do
    echo -n "$param "
    rgrep $param eve/eve | wc -l
done | grep ' 0$' 
```

Result:
```
OPTMIMIZE_PAGINATION_FOR_SPEED 0
ITEM_TITLE 0
MONGO_AUTHDBNAME 0
MONGO_MAX_POOL_SIZE 0
MONGO_SOCKET_TIMEOUT_MS 0
MONGO_CONNECT_TIMEOUT_MS 0
MONGO_REPLICA_SET 0
MONGO_READ_PREFERENCE 0
VALIDATION_ERROR_AS_STRING 0
```

For the current pypi version of Eve:
```bash
wget https://pypi.python.org/packages/17/24/cab40bd243f13ec8f2f5a98eb9a051f5bff60699fadea0096111986e7e0e/Eve-0.6.4.tar.gz
tar xvf Eve-0.6.4.tar.gz
for param in `python eve-get-config-params.py`; do
    echo -n "$param "
    rgrep $param Eve-0.6.4/eve | wc -l
done | grep ' 0$' 
```
Result:
```
OPTMIMIZE_PAGINATION_FOR_SPEED 0
QUERY_AGGREGATION 0
ITEM_TITLE 0
ENFORCE_IF_MATCH 0
MONGO_OPTIONS 0
MONGO_AUTHDBNAME 0
MONGO_MAX_POOL_SIZE 0
MONGO_SOCKET_TIMEOUT_MS 0
MONGO_CONNECT_TIMEOUT_MS 0
MONGO_REPLICA_SET 0
MONGO_READ_PREFERENCE 0
MULTIPART_FORM_FIELDS_AS_JSON 0
AUTO_COLLAPSE_MULTI_KEYS 0
AUTO_CREATE_LISTS 0
OPLOG_CHANGE_METHODS 0
OPLOG_RETURN_EXTRA_FIELD 0
VALIDATION_ERROR_AS_STRING 0
```

**Comment by gmargari** [comment]
Background: I want to catch the case where mongodb is not running, because in that case the client request hangs up for 30 seconds (the default timeout for the connection to the db). I think it would be better to immediately return a "500 internal server error" in case mongodb is not running (and log the error so admin can be informed).

So I tried decreasing the params `MONGO_SOCKET_TIMEOUT_MS` and `MONGO_CONNECT_TIMEOUT_MS`, only to find out after some search that they do not exist in code. They existed initially and were removed at some point? Is there any easy way to catch the case mongodb is not running and quickly send a 500 error back to client?

**Comment by bomb-on** [comment]
If this is of any help, those 2 params are part of [Flask-PyMongo](http://flask-pymongo.readthedocs.io/en/latest/#Configuration) configuration, not Eve. Just out of curiosity, why are you reading all config params from a website?

**Comment by gmargari** [comment]
Yes I found out that theser parameters are from pymongo. But since they were also documented on Eve I used them and I supposed they would be passed to the underlying connection to mongodb.

After I noticed that these params didn't exist in Eve code, I just used that simple script to see which other params are documented but are not used, in order to ensure I'm not using any other no-op parameter.

**Comment by bomb-on** [comment]
Why don't you try [something like this](http://stackoverflow.com/a/30539401/175793) to check if MongoDB is available?

**Comment by gmargari** [comment]
That's exactly what I would like to do, but on the Eve level. I don't want to hack the underlying code that connects to MongoDB. I had in my mind to just set the timeout to a low value and then catch the `pymongo.errors.ServerSelectionTimeoutError` exception.
