### ISSUE TITLE
Support for by-method settings within by-endpoint settings

### ISSUE THREAD

**Issue by impulsemk** [pyeve/eve#973]
Willing to put in the work myself on this; just want to see if there's demand for it or if I'm going about this  in the wrong way or if I'm dumb and there's already a way to do this:

Currently, the most granular level you can configure Eve for is at the by-endpoint level, which means that those settings apply for all methods within that endpoint (GET, PUT, POST, DELETE, etc). I seem to keep hitting on cases where I want by-method control of configuration in a lot of cases; for example, disabling schema validation for PUTs only, or turning on HATEOAS for only GETs.

I propose that we allow for dicts to be passed into both "resource_methods" and "item_methods", and within the values for the dict we'll have by-method settings that largely mirror the settings of by-endpoint:

```
my_resource = {
    # 'title' tag used in item links. Defaults to the resource title minus
    # the final, plural 's' (works fine in most cases but not for 'people')
    'item_title': 'resource',
    
    # by default the standard item entry point is defined as
    # '/people/<ObjectId>'. We leave it untouched, and we also enable an
    # additional read-only entry point. This way consumers can also perform
    # GET requests at '/people/<lastname>'.
    'additional_lookup': {
        'url': 'regex("[\w]+")',
        'field': 'userid'
    },
    
    # most global settings can be overridden at resource level
    'resource_methods': {'GET':None, 'POST':None},
    'item_methods': {
       'GET':None, 
       'PUT': {'transparent_schema_rules': True},
       'PATCH':{'schema':ALT_SCHEMA}
    },
    'schema': MY_SCHEMA
}

```
Methods with None or {} values means to just use the by-endpoint settings for that method. The semantic is waterfall override, just like the by-endpoint settings, in the order of Global -> Endpoint -> Method settings. Obviously list input would be the way it is now.

**Comment by impulsemk** [comment]
It also occurred to me that we probably would want to forbid certain settings from being set at the by-method level since it could break logic downstream (maybe 'schema'? Would need to look at the code), or it just doesn't make sense ('item_title' is not relevant at all to by-method).

**Comment by nicolaiarocci** [comment]
Interesting. Personally I don't need it, but I can imagine  it could be powerful in some use cases. Let's see if there's interest for this.

**Comment by nikitph** [comment]
i would like this
