### ISSUE TITLE
How to make a custom query from mongodb and make json response or xml response

### ISSUE THREAD

**Issue by toplinuxsir** [pyeve/eve#991]
How to make a custom query from mongodb and make json response or xml response
For example:
   I want to query a colleciton named "testcol"
  
@app.route("/api/query")
def custom():
   objs  = app.driver.db.find("testcol", query_cond)
   return send_response("testcol", objs)

but It dose not work 

How to  ?
Thanks

**Comment by Amedeo91** [comment]
objs is not list nor dictionary, but a cursor. Moreover, query_cond is not defined anywhere...
