### ISSUE TITLE
Request: Add support for reraising exceptions in post_internal

### ISSUE THREAD

**Issue by nanaky92** [pyeve/eve#997]
Hello all, 

I think it would be interesting to have a mechanism to reraise exceptions inside post_internal as there is one inside the put_internal or patch_internal (if we declare our custom exceptions as HTTP exceptions). Something similar to this:

```
    except exceptions.HTTPException as e:
        raise e

```
in the lines previous to:

`    except Exception as e:
`

I will explain my usecase:

I am using the eve.io.validator for Eve. When the validator fails (as it should), I raise several exceptions defined by me that contain the fields that I want to display to the user: a title, some codes, etc. Then, I use the error handlers provided by flask for capturing this exception and sending it to the user in the proper way. 

In the endpoints that I've defined, I dont have any problems because I don't try to catch the exception. When I use eve's default patch or put, there is no problem as long as I define my own exception as HTTPExceptions. 

However, when I use eve's post method, there is no mechanism to reraise a exception and I would have to use the post_post_callback hook to try to extract the information, refactor it and send the appropriate response.  It would be more consistent with the rest of the application if I could simply raise the exception and not have to worry about to "redo" the data that Eve's default exception handler has messed up with.

This is my first time ever as a contributor, I hope I can start contributing to this framework :-)

**Comment by Amedeo91** [comment]
I had some similar issue with patch or put. In order to skip the except Exception, I will suggest inheriting your custom exception from the BaseException instead of the Exception class. Otherwise, if you want to add some special handler inside all the try catch, I think we should create some generic set-up to pass to the Eve initialiser, but I wonder if it is worthed.
